# Import LLibrary

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Data Preparation

In [ ]:
raw_data = pd.read_csv('/kaggle/input/hearth-disease-recognition/train.csv')

In [ ]:
raw_data.head()

,ID,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,train_000001,No,Yes,Yes,Yes,40.68,Yes,No,No,No,No,Yes,No,Very Poor,Yes,Female,High school graduate,"$15,000 to less than $20,000",64,Yes
1,train_000002,No,No,No,No,24.36,Yes,No,No,Yes,No,No,Yes,Fair,No,Female,College graduate,"Less than $10,000",50,No
2,train_000003,No,Yes,Yes,Yes,27.33,No,No,No,No,No,Yes,Yes,Very Poor,Yes,Female,High school graduate,"$75,000 or more",61,Yes
3,train_000004,No,Yes,No,Yes,27.01,No,No,No,Yes,No,Yes,No,Good,No,Female,Some high school,"$35,000 to less than $50,000",74,Yes
4,train_000005,NaN,Yes,Yes,Yes,34.56,Yes,No,No,Yes,No,Yes,Yes,Very Poor,Yes,Male,Some high school,"$15,000 to less than $20,000",98,Yes

## Check missing Data

In [ ]:
def value_counts(data,col):
    return data[col].value_counts()

def checkall_null(data):
    return data.isnull().sum()

def check_info(data):
    return data.info()

In [ ]:
check_info(raw_data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223084 entries, 0 to 223083
Data columns (total 20 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ID                                      223084 non-null  object
 1   History of HeartDisease or Attack       221390 non-null  object
 2   High Blood Pressure                     223084 non-null  object
 3   Told High Cholesterol                   190898 non-null  object
 4   Cholesterol Checked                     223084 non-null  object
 5   Body Mass Index                         211302 non-null  float64
 6   Smoked 100+ Cigarettes                  223083 non-null  object
 7   Diagnosed Stroke                        223084 non-null  object
 8   Diagnosed Diabetes                      223081 non-null  object
 9   Leisure Physical Activity               223084 non-null  object
 10  Heavy Alcohol Consumption               223084 non-null  object
 11  Health Care Coverage                    223084 non-null  object
 12  Doctor Visit Cost Barrier               223083 non-null  object
 13  General Health                          223083 non-null  object
 14  Difficulty Walking                      223081 non-null  object
 15  Sex                                     223084 non-null  object
 16  Education Level                         223084 non-null  object
 17  Income Level                            223084 non-null  object
 18  Age                                     223084 non-null  int64
 19  Vegetable or Fruit Intake (1+ per Day)  223084 non-null  object
dtypes: float64(1), int64(1), object(18)
memory usage: 34.0+ MB

In [ ]:
checkall_null(raw_data)

ID                                            0
History of HeartDisease or Attack          1694
High Blood Pressure                           0
Told High Cholesterol                     32186
Cholesterol Checked                           0
Body Mass Index                           11782
Smoked 100+ Cigarettes                        1
Diagnosed Stroke                              0
Diagnosed Diabetes                            3
Leisure Physical Activity                     0
Heavy Alcohol Consumption                     0
Health Care Coverage                          0
Doctor Visit Cost Barrier                     1
General Health                                1
Difficulty Walking                            3
Sex                                           0
Education Level                               0
Income Level                                  0
Age                                           0
Vegetable or Fruit Intake (1+ per Day)        0
dtype: int64

In [ ]:
# History of HeartDisease or Attack 1694 (Yes / No) Nominal Scale
# Told High Cholesterol (Intreval Scales)

value_counts(raw_data,'Smoked 100+ Cigarettes')

Smoked 100+ Cigarettes
No     125888
Yes     97195
Name: count, dtype: int64

In [ ]:
data = raw_data.copy()

In [ ]:
# df_yes = data[data['History of HeartDisease or Attack'] == 'Yes'].sample(n=18068, random_state=42)
# df_no = data[data['History of HeartDisease or Attack'] == 'No'].sample(n=20000, random_state=42)
#data = pd.concat([df_yes, df_no], ignore_index=True)

In [ ]:
data.dropna()
for col in data.columns:
    print(value_counts(data,col))

ID
train_000001    1
train_148728    1
train_148717    1
train_148718    1
train_148719    1
               ..
train_074365    1
train_074366    1
train_074367    1
train_074368    1
train_223084    1
Name: count, Length: 223084, dtype: int64
History of HeartDisease or Attack
No     203322
Yes     18068
Name: count, dtype: int64
High Blood Pressure
No     136346
Yes     86738
Name: count, dtype: int64
Told High Cholesterol
No     110468
Yes     80430
Name: count, dtype: int64
Cholesterol Checked
Yes    183784
No      39300
Name: count, dtype: int64
Body Mass Index
24.92    208
26.48    207
25.64    206
26.63    206
24.93    202
        ...
75.02      1
74.53      1
77.38      1
73.58      1
60.36      1
Name: count, Length: 4907, dtype: int64
Smoked 100+ Cigarettes
No     125888
Yes     97195
Name: count, dtype: int64
Diagnosed Stroke
No     214928
Yes      8156
Name: count, dtype: int64
Diagnosed Diabetes
No     193459
Yes     29622
Name: count, dtype: int64
Leisure Physical Activity
Yes    166976
No      56108
Name: count, dtype: int64
Heavy Alcohol Consumption
No     210132
Yes     12952
Name: count, dtype: int64
Health Care Coverage
Yes    206732
No      16352
Name: count, dtype: int64
Doctor Visit Cost Barrier
No     200559
Yes     22524
Name: count, dtype: int64
General Health
Good         77536
Fair         67632
Excellent    40312
Poor         27479
Very Poor    10124
Name: count, dtype: int64
Difficulty Walking
No     187729
Yes     35352
Name: count, dtype: int64
Sex
Female    126195
Male       96889
Name: count, dtype: int64
Education Level
College graduate                    88314
Some college or technical school    62322
High school graduate                58064
Some high school                     9662
Elementary                           4482
Never attended school                 240
Name: count, dtype: int64
Income Level
$75,000 or more                  73702
$50,000 to less than $75,000     37029
$35,000 to less than $50,000     32394
$25,000 to less than $35,000     23647
$20,000 to less than $25,000     19089
$15,000 to less than $20,000     15669
($10,000 to less than $15,000    11078
Less than $10,000                10476
Name: count, dtype: int64
Age
61     5377
63     5275
62     5238
60     5223
64     5196
       ...
85      628
100     624
84      604
81      596
97      594
Name: count, Length: 83, dtype: int64
Vegetable or Fruit Intake (1+ per Day)
Yes    194768
No      28316
Name: count, dtype: int64

In [ ]:
#data = data.dropna(subset=['History of HeartDisease or Attack'])

In [ ]:
#data.info()

In [ ]:
data.isnull().sum()

ID                                            0
History of HeartDisease or Attack          1694
High Blood Pressure                           0
Told High Cholesterol                     32186
Cholesterol Checked                           0
Body Mass Index                           11782
Smoked 100+ Cigarettes                        1
Diagnosed Stroke                              0
Diagnosed Diabetes                            3
Leisure Physical Activity                     0
Heavy Alcohol Consumption                     0
Health Care Coverage                          0
Doctor Visit Cost Barrier                     1
General Health                                1
Difficulty Walking                            3
Sex                                           0
Education Level                               0
Income Level                                  0
Age                                           0
Vegetable or Fruit Intake (1+ per Day)        0
dtype: int64

![image.png](attachment:b2bde1a1-989f-4987-be36-52a1e1ec567d.png)![image.png](attachment:02fdf94e-f9bf-4252-9315-ca87e173d85b.png)

In [ ]:
def clean_data(data):
    # Check if duplicated
    if data.duplicated().sum():
        data = data.drop_duplicated()
    data = data.dropna()
    df_yes = data[data['History of HeartDisease or Attack'] == 'Yes'].sample(n=len(data[data['History of HeartDisease or Attack'] == 'Yes']), random_state=42)
    df_no = data[data['History of HeartDisease or Attack'] == 'No'].sample(n=18000, random_state=42)
    data = pd.concat([df_yes, df_no], ignore_index=True)

    # Try fillna with median on BMI
    # data['Body Mass Index'] = data['Body Mass Index'].fillna(data['Body Mass Index'].median())

    # Remove Outliers
    numeric_cols = data.select_dtypes(include='number').columns
    for col in numeric_cols:
        Q1 = data[col].quantile(0.15)
        Q3 = data[col].quantile(0.85)
        IQR = Q3 - Q1
        print(Q1 - 1.5 * IQR)
        print(Q3 + 1.5 * IQR)
        outliers = data[(data[col] < Q1 - 1.5 * IQR) | (data[col] > Q3 + 1.5 * IQR)]
        print(f"{col}: {len(outliers)} potential outliers")

    # Input Outlier values
    data = data[data['Body Mass Index'] >= 5.914999999999996]
    data = data[data['Body Mass Index'] <= 50.115]
    return data

In [ ]:
cleaned_data = clean_data(data)

5.530000000000005
52.00999999999999
Body Mass Index: 278 potential outliers
-0.5
123.5
Age: 0 potential outliers

In [ ]:
cleaned_data

,ID,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,train_163195,Yes,Yes,Yes,Yes,23.53,No,No,Yes,No,No,Yes,No,Very Poor,Yes,Female,High school graduate,"$15,000 to less than $20,000",88,Yes
1,train_060816,Yes,No,Yes,Yes,26.85,No,No,Yes,No,No,Yes,Yes,Poor,Yes,Male,High school graduate,"Less than $10,000",44,Yes
2,train_027128,Yes,Yes,Yes,Yes,41.05,Yes,No,No,Yes,No,Yes,No,Good,No,Male,College graduate,"$75,000 or more",67,Yes
3,train_049893,Yes,No,No,Yes,24.01,Yes,No,No,No,No,Yes,No,Fair,Yes,Male,Some college or technical school,"$20,000 to less than $25,000",66,No
4,train_118177,Yes,Yes,No,Yes,29.66,No,No,No,No,No,Yes,No,Fair,No,Male,Some college or technical school,"$75,000 or more",99,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34933,train_093521,No,No,No,Yes,24.22,No,No,No,Yes,No,Yes,No,Excellent,No,Male,College graduate,"$75,000 or more",39,Yes
34934,train_155413,No,Yes,No,Yes,31.62,No,No,No,Yes,No,Yes,No,Fair,Yes,Male,High school graduate,"$20,000 to less than $25,000",63,Yes
34935,train_222971,No,No,Yes,Yes,25.75,No,No,No,No,No,Yes,No,Fair,No,Female,Some college or technical school,"$15,000 to less than $20,000",72,No
34936,train_096622,No,Yes,No,Yes,31.67,Yes,No,No,Yes,No,Yes,No,Poor,Yes,Female,Some college or technical school,"$35,000 to less than $50,000",73,Yes
34937,train_035887,No,Yes,No,Yes,40.03,Yes,No,Yes,Yes,No,Yes,No,Poor,Yes,Female,High school graduate,"($10,000 to less than $15,000",67,Yes

In [ ]:
def create_new_features(data):

    binary_map = {"Yes": 1, "No": 0}
    binary_cols = [
        "High Blood Pressure", "Told High Cholesterol", "Cholesterol Checked",
        "Smoked 100+ Cigarettes", "Diagnosed Stroke", "Diagnosed Diabetes",
        "Leisure Physical Activity", "Heavy Alcohol Consumption",
        "Health Care Coverage", "Doctor Visit Cost Barrier",
        "Difficulty Walking", "Vegetable or Fruit Intake (1+ per Day)"
    ]

    for col in binary_cols:
        # Create a new binary column with suffix '_bin'
        if data[col].dtype == object:
            data[col + "_bin"] = data[col].map(binary_map)
        else:
            data[col + "_bin"] = train_data[col]

    def categorize_bmi(bmi): # GOOD
        if bmi < 18.5:
            return "Underweight"
        elif bmi < 25:
            return "Normal weight"
        elif bmi < 30:
            return "Overweight"
        elif bmi < 40:
            return "Obese"
        else:
            return 'Morbidly Obese'

    data['BMI Category'] = data['Body Mass Index'].apply(categorize_bmi)
    category_order = ['Underweight', 'Normal weight', 'Overweight', 'Obese', 'Morbidly Obese']
    cat_type = pd.CategoricalDtype(categories=category_order, ordered=True)
    data['BMI Category'] = data['BMI Category'].astype(cat_type).cat.codes

    category_order = ['Never attended school', 'Elementary', 'Some high school', 'High school graduate', 'Some college or technical school','College graduate']
    cat_type = pd.CategoricalDtype(categories=category_order, ordered=True)
    data['education_ordinal'] = data['Education Level'].astype(cat_type).cat.codes

    category_order = ['Less than $10,000', '($10,000 to less than $15,000', '$15,000 to less than $20,000' ,
                      '$20,000 to less than $25,000', '$25,000 to less than $35,000' , '$35,000 to less than $50,000' ,
                      '$50,000 to less than $75,000', '$75,000 or more']
    cat_type = pd.CategoricalDtype(categories=category_order, ordered=True)
    data['income_ordinal'] = data['Income Level'].astype(cat_type).cat.codes

    category_order = ['Less than $10,000', '($10,000 to less than $15,000', '$15,000 to less than $20,000' ,
                      '$20,000 to less than $25,000', '$25,000 to less than $35,000' , '$35,000 to less than $50,000' ,
                      '$50,000 to less than $75,000', '$75,000 or more']
    cat_type = pd.CategoricalDtype(categories=category_order, ordered=True)
    data['income_ordinal'] = data['Income Level'].astype(cat_type).cat.codes

    category_order = ['Male', 'Female']
    cat_type = pd.CategoricalDtype(categories=category_order, ordered=True)
    data['Sex'] = data['Sex'].astype(cat_type).cat.codes

    data['Obesity Risk'] = ((data['Body Mass Index'] >= 30) & (data['Leisure Physical Activity'] == 'No')).astype(int)


    columns_to_drop = [
        "High Blood Pressure", "Told High Cholesterol", "Cholesterol Checked",
        "Smoked 100+ Cigarettes", "Diagnosed Stroke", "Diagnosed Diabetes",
        "Leisure Physical Activity", "Heavy Alcohol Consumption",
        "Health Care Coverage", "Doctor Visit Cost Barrier",
        "Difficulty Walking", "Vegetable or Fruit Intake (1+ per Day)",
        "Leisure Physical Activity","General Health","Income Level",'Education Level'
    ]
    data = data.drop(columns=columns_to_drop)
    return data

In [ ]:
train_data = create_new_features(cleaned_data)

In [ ]:
#columns_to_drop = [
#        "High Blood Pressure", "Told High Cholesterol", "Cholesterol Checked",
#        "Smoked 100+ Cigarettes", "Diagnosed Stroke", "Diagnosed Diabetes",
#        "Leisure Physical Activity", "Heavy Alcohol Consumption",
#        "Health Care Coverage", "Doctor Visit Cost Barrier",
#        "Difficulty Walking", "Vegetable or Fruit Intake (1+ per Day)",
#        "Leisure Physical Activity","General Health","Income Level",'Education Level'
#    ]
#train_data = train_data.drop(columns=columns_to_drop)

In [ ]:
train_data.Sex.value_counts()

Sex
0    17305
1    17277
Name: count, dtype: int64

In [ ]:
train_data.head()

,ID,History of HeartDisease or Attack,Body Mass Index,Sex,Age,High Blood Pressure_bin,Told High Cholesterol_bin,Cholesterol Checked_bin,Smoked 100+ Cigarettes_bin,Diagnosed Stroke_bin,...,Leisure Physical Activity_bin,Heavy Alcohol Consumption_bin,Health Care Coverage_bin,Doctor Visit Cost Barrier_bin,Difficulty Walking_bin,Vegetable or Fruit Intake (1+ per Day)_bin,BMI Category,education_ordinal,income_ordinal,Obesity Risk
0,train_163195,Yes,23.53,1,88,1,1,1,0,0,...,0,0,1,0,1,1,1,3,2,0
1,train_060816,Yes,26.85,0,44,0,1,1,0,0,...,0,0,1,1,1,1,2,3,0,0
2,train_027128,Yes,41.05,0,67,1,1,1,1,0,...,1,0,1,0,0,1,4,5,7,0
3,train_049893,Yes,24.01,0,66,0,0,1,1,0,...,0,0,1,0,1,0,1,4,3,0
4,train_118177,Yes,29.66,0,99,1,0,1,0,0,...,0,0,1,0,0,1,2,4,7,0

In [ ]:
# value_counts(cleaned_data,'Income Level')

In [ ]:
# list(cleaned_data['General Health'].unique())

In [ ]:
# cleaned_data

In [ ]:
# value_counts(data,'Told High Cholesterol')

In [ ]:
#numeric_cols = data.select_dtypes(include='number').columns
#for col in numeric_cols:
   # data[col].describe()
   # Q1 = data[col].quantile(0.15)
   # Q3 = data[col].quantile(0.85)

   # IQR = Q3 - Q1
   # print(Q1 - 1.5 * IQR)
   # print(Q3 + 1.5 * IQR)
   # outliers = data[(data[col] < Q1 - 1.5 * IQR) | (data[col] > Q3 + 1.5 * IQR)]
   # print(f"{col}: {len(outliers)} potential outliers")

In [ ]:
#data_no_outlier = data[data['Body Mass Index'] >= 5.914999999999996]
#data_no_outlier = data[data['Body Mass Index'] <= 50.115]

In [ ]:
#data_no_outlier.info()#

In [ ]:
#d = list(data_no_outlier['Body Mass Index'])
#fig = plt.figure(figsize =(10, 7))

#plt.boxplot(d)
#plt.show()

In [ ]:
#data_no_outlier.head()

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34582 entries, 0 to 34937
Data columns (total 21 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   ID                                          34582 non-null  object
 1   History of HeartDisease or Attack           34582 non-null  object
 2   Body Mass Index                             34582 non-null  float64
 3   Sex                                         34582 non-null  int8
 4   Age                                         34582 non-null  int64
 5   High Blood Pressure_bin                     34582 non-null  int64
 6   Told High Cholesterol_bin                   34582 non-null  int64
 7   Cholesterol Checked_bin                     34582 non-null  int64
 8   Smoked 100+ Cigarettes_bin                  34582 non-null  int64
 9   Diagnosed Stroke_bin                        34582 non-null  int64
 10  Diagnosed Diabetes_bin                      34582 non-null  int64
 11  Leisure Physical Activity_bin               34582 non-null  int64
 12  Heavy Alcohol Consumption_bin               34582 non-null  int64
 13  Health Care Coverage_bin                    34582 non-null  int64
 14  Doctor Visit Cost Barrier_bin               34582 non-null  int64
 15  Difficulty Walking_bin                      34582 non-null  int64
 16  Vegetable or Fruit Intake (1+ per Day)_bin  34582 non-null  int64
 17  BMI Category                                34582 non-null  int8
 18  education_ordinal                           34582 non-null  int8
 19  income_ordinal                              34582 non-null  int8
 20  Obesity Risk                                34582 non-null  int64
dtypes: float64(1), int64(14), int8(4), object(2)
memory usage: 4.9+ MB

In [ ]:
train_data['History of HeartDisease or Attack'] = train_data['History of HeartDisease or Attack'].fillna('No')

In [ ]:
train_data['History of HeartDisease or Attack'].value_counts()

History of HeartDisease or Attack
No     17840
Yes    16742
Name: count, dtype: int64

In [ ]:
train_data.isnull().sum()

ID                                            0
History of HeartDisease or Attack             0
Body Mass Index                               0
Sex                                           0
Age                                           0
High Blood Pressure_bin                       0
Told High Cholesterol_bin                     0
Cholesterol Checked_bin                       0
Smoked 100+ Cigarettes_bin                    0
Diagnosed Stroke_bin                          0
Diagnosed Diabetes_bin                        0
Leisure Physical Activity_bin                 0
Heavy Alcohol Consumption_bin                 0
Health Care Coverage_bin                      0
Doctor Visit Cost Barrier_bin                 0
Difficulty Walking_bin                        0
Vegetable or Fruit Intake (1+ per Day)_bin    0
BMI Category                                  0
education_ordinal                             0
income_ordinal                                0
Obesity Risk                                  0
dtype: int64

# Train MODEL

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import fbeta_score as f2

import warnings
warnings.filterwarnings('ignore')

In [ ]:
features = train_data.drop(['ID', 'History of HeartDisease or Attack'], axis=1)
target = train_data['History of HeartDisease or Attack']

X_train, X_val, Y_train, Y_val = train_test_split(
    features,
    target,
    random_state=3200,
    test_size=0.20)


X_train.shape, X_val.shape

((27665, 19), (6917, 19))

In [ ]:
model = CatBoostClassifier(iterations=2,
                           learning_rate=1,
                           depth=2)

In [ ]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)

In [ ]:
model = CatBoostClassifier(verbose=5,
                           iterations=1000,
                           loss_function='Logloss',
                           early_stopping_rounds=100,
                           depth = 8,
                           custom_metric=['AUC'])

model.fit(X_train, Y_train,
          eval_set=(X_val, Y_val))

y_train = model.predict(X_train)
y_val = model.predict(X_val)

Learning rate set to 0.071956
0:	learn: 0.6640959	test: 0.6645793	best: 0.6645793 (0)	total: 14.9ms	remaining: 14.9s
5:	learn: 0.5722064	test: 0.5764886	best: 0.5764886 (5)	total: 84.1ms	remaining: 13.9s
10:	learn: 0.5297937	test: 0.5363718	best: 0.5363718 (10)	total: 157ms	remaining: 14.1s
15:	learn: 0.5093784	test: 0.5193643	best: 0.5193643 (15)	total: 235ms	remaining: 14.5s
20:	learn: 0.4967694	test: 0.5097862	best: 0.5097862 (20)	total: 313ms	remaining: 14.6s
25:	learn: 0.4898568	test: 0.5046877	best: 0.5046877 (25)	total: 380ms	remaining: 14.3s
30:	learn: 0.4852034	test: 0.5019289	best: 0.5019289 (30)	total: 445ms	remaining: 13.9s
35:	learn: 0.4814300	test: 0.5000998	best: 0.5000998 (35)	total: 508ms	remaining: 13.6s
40:	learn: 0.4781701	test: 0.4986820	best: 0.4986820 (40)	total: 571ms	remaining: 13.4s
45:	learn: 0.4757535	test: 0.4979033	best: 0.4979033 (45)	total: 634ms	remaining: 13.2s
50:	learn: 0.4734333	test: 0.4970748	best: 0.4970748 (50)	total: 699ms	remaining: 13s
55:	learn: 0.4716741	test: 0.4965888	best: 0.4965888 (55)	total: 760ms	remaining: 12.8s
60:	learn: 0.4697671	test: 0.4963051	best: 0.4963051 (60)	total: 822ms	remaining: 12.7s
65:	learn: 0.4677435	test: 0.4960852	best: 0.4960852 (65)	total: 884ms	remaining: 12.5s
70:	learn: 0.4662505	test: 0.4961034	best: 0.4960852 (65)	total: 943ms	remaining: 12.3s
75:	learn: 0.4650005	test: 0.4960991	best: 0.4959972 (72)	total: 998ms	remaining: 12.1s
80:	learn: 0.4631483	test: 0.4959265	best: 0.4959265 (80)	total: 1.06s	remaining: 12s
85:	learn: 0.4615398	test: 0.4959933	best: 0.4959265 (80)	total: 1.12s	remaining: 11.9s
90:	learn: 0.4601280	test: 0.4961250	best: 0.4959237 (87)	total: 1.18s	remaining: 11.8s
95:	learn: 0.4587821	test: 0.4964102	best: 0.4959237 (87)	total: 1.25s	remaining: 11.8s
100:	learn: 0.4575489	test: 0.4963965	best: 0.4959237 (87)	total: 1.31s	remaining: 11.7s
105:	learn: 0.4563375	test: 0.4964093	best: 0.4959237 (87)	total: 1.37s	remaining: 11.6s
110:	learn: 0.4554131	test: 0.4965396	best: 0.4959237 (87)	total: 1.43s	remaining: 11.5s
115:	learn: 0.4541624	test: 0.4967076	best: 0.4959237 (87)	total: 1.5s	remaining: 11.4s
120:	learn: 0.4528952	test: 0.4967419	best: 0.4959237 (87)	total: 1.56s	remaining: 11.3s
125:	learn: 0.4515999	test: 0.4970178	best: 0.4959237 (87)	total: 1.62s	remaining: 11.3s
130:	learn: 0.4501395	test: 0.4972073	best: 0.4959237 (87)	total: 1.69s	remaining: 11.2s
135:	learn: 0.4488696	test: 0.4973125	best: 0.4959237 (87)	total: 1.76s	remaining: 11.2s
140:	learn: 0.4473269	test: 0.4975154	best: 0.4959237 (87)	total: 1.82s	remaining: 11.1s
145:	learn: 0.4459285	test: 0.4977998	best: 0.4959237 (87)	total: 1.88s	remaining: 11s
150:	learn: 0.4446417	test: 0.4980188	best: 0.4959237 (87)	total: 1.95s	remaining: 10.9s
155:	learn: 0.4434177	test: 0.4981363	best: 0.4959237 (87)	total: 2.01s	remaining: 10.9s
160:	learn: 0.4421132	test: 0.4982909	best: 0.4959237 (87)	total: 2.07s	remaining: 10.8s
165:	learn: 0.4409799	test: 0.4985608	best: 0.4959237 (87)	total: 2.13s	remaining: 10.7s
170:	learn: 0.4397141	test: 0.4988738	best: 0.4959237 (87)	total: 2.2s	remaining: 10.7s
175:	learn: 0.4383697	test: 0.4991132	best: 0.4959237 (87)	total: 2.26s	remaining: 10.6s
180:	learn: 0.4372129	test: 0.4992278	best: 0.4959237 (87)	total: 2.32s	remaining: 10.5s
185:	learn: 0.4361086	test: 0.4992593	best: 0.4959237 (87)	total: 2.39s	remaining: 10.4s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.4959237072
bestIteration = 87

Shrink model to first 88 iterations.

In [ ]:
print("Training F2 : ", f2(Y_train, y_train,average=None, beta=0.5))
print("Validation F2: ", f2(Y_val, y_val,average=None, beta=0.5))

Training F2 :  [0.79766595 0.76096068]
Validation F2:  [0.77402629 0.74194952]

In [ ]:
Y_train

27616     No
29575     No
19322     No
8942     Yes
6488     Yes
        ...
29362     No
2199     Yes
13866    Yes
34762     No
29659     No
Name: History of HeartDisease or Attack, Length: 27665, dtype: object

# PREDICT TEST DATA BOI WIth CATBOOST

In [ ]:
test_data = pd.read_csv('/kaggle/input/hearth-disease-recognition/test.csv')

In [ ]:
test_data.head()

,ID,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,test_000001,Yes,Yes,Yes,24.84,No,No,No,Yes,No,Yes,No,Good,No,Female,Some college or technical school,"$20,000 to less than $25,000",71,Yes
1,test_000002,Yes,No,Yes,29.08,Yes,No,No,No,No,Yes,No,Fair,No,Female,College graduate,"$50,000 to less than $75,000",61,No
2,test_000003,Yes,Yes,Yes,35.23,Yes,No,No,No,No,Yes,No,Fair,Yes,Female,Some college or technical school,"Less than $10,000",67,Yes
3,test_000004,No,No,Yes,24.78,Yes,No,No,No,No,Yes,No,Fair,No,Female,Some college or technical school,"$50,000 to less than $75,000",50,Yes
4,test_000005,No,No,Yes,27.57,Yes,No,No,No,No,Yes,No,Fair,No,Male,Some college or technical school,"$25,000 to less than $35,000",40,Yes

In [ ]:
test_data.isnull().sum()

ID                                        0
High Blood Pressure                       0
Told High Cholesterol                     0
Cholesterol Checked                       0
Body Mass Index                           0
Smoked 100+ Cigarettes                    0
Diagnosed Stroke                          0
Diagnosed Diabetes                        0
Leisure Physical Activity                 0
Heavy Alcohol Consumption                 0
Health Care Coverage                      0
Doctor Visit Cost Barrier                 0
General Health                            0
Difficulty Walking                        0
Sex                                       0
Education Level                           0
Income Level                              0
Age                                       0
Vegetable or Fruit Intake (1+ per Day)    0
dtype: int64

In [ ]:
test_data = create_new_features(test_data)

In [ ]:
featur = test_data.columns[1:]
featur

Index(['Body Mass Index', 'Sex', 'Age', 'High Blood Pressure_bin',
       'Told High Cholesterol_bin', 'Cholesterol Checked_bin',
       'Smoked 100+ Cigarettes_bin', 'Diagnosed Stroke_bin',
       'Diagnosed Diabetes_bin', 'Leisure Physical Activity_bin',
       'Heavy Alcohol Consumption_bin', 'Health Care Coverage_bin',
       'Doctor Visit Cost Barrier_bin', 'Difficulty Walking_bin',
       'Vegetable or Fruit Intake (1+ per Day)_bin', 'BMI Category',
       'education_ordinal', 'income_ordinal', 'Obesity Risk'],
      dtype='object')

In [ ]:
test_data[featur]

,Body Mass Index,Sex,Age,High Blood Pressure_bin,Told High Cholesterol_bin,Cholesterol Checked_bin,Smoked 100+ Cigarettes_bin,Diagnosed Stroke_bin,Diagnosed Diabetes_bin,Leisure Physical Activity_bin,Heavy Alcohol Consumption_bin,Health Care Coverage_bin,Doctor Visit Cost Barrier_bin,Difficulty Walking_bin,Vegetable or Fruit Intake (1+ per Day)_bin,BMI Category,education_ordinal,income_ordinal,Obesity Risk
0,24.84,1,71,1,1,1,0,0,0,1,0,1,0,0,1,1,4,3,0
1,29.08,1,61,1,0,1,1,0,0,0,0,1,0,0,0,2,5,6,0
2,35.23,1,67,1,1,1,1,0,0,0,0,1,0,1,1,3,4,0,1
3,24.78,1,50,0,0,1,1,0,0,0,0,1,0,0,1,1,4,6,0
4,27.57,0,40,0,0,1,1,0,0,0,0,1,0,0,1,2,4,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74356,22.85,1,47,1,0,1,0,0,0,0,0,1,0,0,1,1,4,1,0
74357,28.27,1,71,1,1,1,1,0,0,0,0,1,0,0,1,2,3,6,0
74358,25.88,1,90,1,1,1,0,0,1,0,0,1,0,1,1,2,5,3,0
74359,23.74,0,59,1,1,1,0,1,0,0,0,1,1,0,0,1,2,1,0
74360,25.64,1,64,1,1,1,0,0,1,1,0,1,0,0,1,2,5,1,0

In [ ]:
test_data.head()

,ID,Body Mass Index,Sex,Age,High Blood Pressure_bin,Told High Cholesterol_bin,Cholesterol Checked_bin,Smoked 100+ Cigarettes_bin,Diagnosed Stroke_bin,Diagnosed Diabetes_bin,Leisure Physical Activity_bin,Heavy Alcohol Consumption_bin,Health Care Coverage_bin,Doctor Visit Cost Barrier_bin,Difficulty Walking_bin,Vegetable or Fruit Intake (1+ per Day)_bin,BMI Category,education_ordinal,income_ordinal,Obesity Risk
0,test_000001,24.84,1,71,1,1,1,0,0,0,1,0,1,0,0,1,1,4,3,0
1,test_000002,29.08,1,61,1,0,1,1,0,0,0,0,1,0,0,0,2,5,6,0
2,test_000003,35.23,1,67,1,1,1,1,0,0,0,0,1,0,1,1,3,4,0,1
3,test_000004,24.78,1,50,0,0,1,1,0,0,0,0,1,0,0,1,1,4,6,0
4,test_000005,27.57,0,40,0,0,1,1,0,0,0,0,1,0,0,1,2,4,4,0

In [ ]:
test_data.Sex.value_counts()

Sex
1    41549
0    32812
Name: count, dtype: int64

In [ ]:
test_features = scaler.transform(test_data.drop(columns='ID'))
test_data['History of HeartDisease or Attack'] = model.predict(test_features)

In [ ]:
test_data

,ID,Body Mass Index,Sex,Age,High Blood Pressure_bin,Told High Cholesterol_bin,Cholesterol Checked_bin,Smoked 100+ Cigarettes_bin,Diagnosed Stroke_bin,Diagnosed Diabetes_bin,...,Heavy Alcohol Consumption_bin,Health Care Coverage_bin,Doctor Visit Cost Barrier_bin,Difficulty Walking_bin,Vegetable or Fruit Intake (1+ per Day)_bin,BMI Category,education_ordinal,income_ordinal,Obesity Risk,History of HeartDisease or Attack
0,test_000001,24.84,1,71,1,1,1,0,0,0,...,0,1,0,0,1,1,4,3,0,Yes
1,test_000002,29.08,1,61,1,0,1,1,0,0,...,0,1,0,0,0,2,5,6,0,No
2,test_000003,35.23,1,67,1,1,1,1,0,0,...,0,1,0,1,1,3,4,0,1,Yes
3,test_000004,24.78,1,50,0,0,1,1,0,0,...,0,1,0,0,1,1,4,6,0,No
4,test_000005,27.57,0,40,0,0,1,1,0,0,...,0,1,0,0,1,2,4,4,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74356,test_074357,22.85,1,47,1,0,1,0,0,0,...,0,1,0,0,1,1,4,1,0,No
74357,test_074358,28.27,1,71,1,1,1,1,0,0,...,0,1,0,0,1,2,3,6,0,Yes
74358,test_074359,25.88,1,90,1,1,1,0,0,1,...,0,1,0,1,1,2,5,3,0,Yes
74359,test_074360,23.74,0,59,1,1,1,0,1,0,...,0,1,1,0,0,1,2,1,0,Yes
74360,test_074361,25.64,1,64,1,1,1,0,0,1,...,0,1,0,0,1,2,5,1,0,Yes

In [ ]:
test_data['History of HeartDisease or Attack'].value_counts()

History of HeartDisease or Attack
No     49942
Yes    24419
Name: count, dtype: int64

In [ ]:
submission = pd.DataFrame(test_data,columns=['ID','History of HeartDisease or Attack'])

In [ ]:
submission.to_csv('submissionHeart.csv',index=False)

# WITH RANDOMFOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Step 1: Drop ID and separate features/target
X = train_data.drop(columns=['ID', 'History of HeartDisease or Attack'])
y = train_data['History of HeartDisease or Attack']

# Step 2: Ensure all features are numeric
X = X.select_dtypes(include=['number'])

# Step 3: Split the data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=3200)

# Step 4: Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

# Step 5: Train Random Forest
model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
model.fit(X_train_scaled, y_train)

# Step 6: Evaluate the model
y_val_pred = model.predict(X_val_scaled)
print(classification_report(y_val, y_val_pred))

# Step 7: Prepare test data (same columns and order as training)
test_X = test_data.drop(columns=['ID'], errors='ignore')  # avoid crash if 'ID' missing
test_X = test_X[X.columns]  # ensure same column order
test_X_scaled = scaler.transform(test_X)

# Step 8: Predict on test data
test_data['History of HeartDisease or Attack'] = model.predict(test_X_scaled)

              precision    recall  f1-score   support

          No       0.75      0.71      0.73      3529
         Yes       0.71      0.76      0.74      3388

    accuracy                           0.73      6917
   macro avg       0.73      0.73      0.73      6917
weighted avg       0.73      0.73      0.73      6917

In [ ]:
test_data

,ID,Body Mass Index,Sex,Age,High Blood Pressure_bin,Told High Cholesterol_bin,Cholesterol Checked_bin,Smoked 100+ Cigarettes_bin,Diagnosed Stroke_bin,Diagnosed Diabetes_bin,...,Heavy Alcohol Consumption_bin,Health Care Coverage_bin,Doctor Visit Cost Barrier_bin,Difficulty Walking_bin,Vegetable or Fruit Intake (1+ per Day)_bin,BMI Category,education_ordinal,income_ordinal,Obesity Risk,History of HeartDisease or Attack
0,test_000001,24.84,1,71,1,1,1,0,0,0,...,0,1,0,0,1,1,4,3,0,Yes
1,test_000002,29.08,1,61,1,0,1,1,0,0,...,0,1,0,0,0,2,5,6,0,No
2,test_000003,35.23,1,67,1,1,1,1,0,0,...,0,1,0,1,1,3,4,0,1,Yes
3,test_000004,24.78,1,50,0,0,1,1,0,0,...,0,1,0,0,1,1,4,6,0,No
4,test_000005,27.57,0,40,0,0,1,1,0,0,...,0,1,0,0,1,2,4,4,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74356,test_074357,22.85,1,47,1,0,1,0,0,0,...,0,1,0,0,1,1,4,1,0,No
74357,test_074358,28.27,1,71,1,1,1,1,0,0,...,0,1,0,0,1,2,3,6,0,No
74358,test_074359,25.88,1,90,1,1,1,0,0,1,...,0,1,0,1,1,2,5,3,0,Yes
74359,test_074360,23.74,0,59,1,1,1,0,1,0,...,0,1,1,0,0,1,2,1,0,Yes
74360,test_074361,25.64,1,64,1,1,1,0,0,1,...,0,1,0,0,1,2,5,1,0,No

In [ ]:
test_data['History of HeartDisease or Attack'].value_counts()
submission = pd.DataFrame(test_data,columns=['ID','History of HeartDisease or Attack'])

In [ ]:
submission.to_csv('submissionHeartRandom.csv',index=False)