# Download data

In [ ]:
%%capture
! pip install -q kaggle

In [ ]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c crime-charges-analysis

mkdir: cannot create directory ‘/root/.kaggle’: File exists
cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 4, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.11/dist-packages/kaggle/__init__.py", line 6, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.11/dist-packages/kaggle/api/kaggle_api_extended.py", line 434, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method. See setup instructions at https://github.com/Kaggle/kaggle-api/

In [ ]:
!unzip /content/crime-charges-analysis.zip
import pandas as pd
import numpy as np
import os
import gc
from tqdm import tqdm

unzip:  cannot find or open /content/crime-charges-analysis.zip, /content/crime-charges-analysis.zip.zip or /content/crime-charges-analysis.zip.ZIP.

In [ ]:
import pandas as pd
import numpy as np
import os
import gc
from tqdm import tqdm

In [ ]:
submit = pd.read_csv('/content/submission.csv')
train = pd.read_csv('/content/train.csv')

# prep data

In [ ]:
train.head()

,id,story,answers
0,OhbVrpoiVg,จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้...,"[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]"
1,RV5IfLBcbf,จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเด...,"[{'จิรศักก์': '[1]'}, {'ไขนภา': '[1]'}]"
2,noGMbJmTPS,คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกร...,"[{'คมกาญจน์': '[2,4,5]'}, {'จิรานุวัตร': '[6]'}]"
3,IAoCLrZ3aW,ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพ...,[{'ขจรพงค์': '[3]'}]
4,ZkSBvrjn9W,กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร...,"[{'กิมใจ': '[2,5,7]'}, {'ขนิฐชีพ': '[5]'}]"

In [ ]:
train['story'].tolist()[:5]

['จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้ปืนจี้ชิงเงินสดจากสถานีขนส่ง',
 'จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเดินตกบันไดด้วยความประมาทส่งผลให้ตนเองขาหัก',
 'คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกรุกเข้าหลังร้านเพื่อขโมยของ มีผลให้เกิดความเสียหายต่อทรัพย์สิน ขณะที่จิรานุวัตรฉ้อโกงผ่านโทรศัพท์',
 'ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพร้อมผู้โดยสาร',
 'กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร้านทอง และขโมยทองที่บรรทุกมา ส่วนขนิฐชีพทุบทำลายกล้องวงจรปิดด้วยความสะใจเฉยๆ']

In [ ]:
train['answers'].tolist()[:5]

["[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]",
 "[{'จิรศักก์': '[1]'}, {'ไขนภา': '[1]'}]",
 "[{'คมกาญจน์': '[2,4,5]'}, {'จิรานุวัตร': '[6]'}]",
 "[{'ขจรพงค์': '[3]'}]",
 "[{'กิมใจ': '[2,5,7]'}, {'ขนิฐชีพ': '[5]'}]"]

In [ ]:
import ast
def convert_dict_list_strings(data):
    result = []
    for item in data:
        try:
            dict_list = ast.literal_eval(item)  # Convert string to list of dicts
            formatted = ', '.join([f"'{k}': {v}" for d in dict_list for k, v in d.items()])
            result.append(f"[{formatted}]")
        except Exception as e:
            print(f"Error parsing: {item}\n{e}")
            result.append("[]")  # fallback if parsing fails
    return result

In [ ]:
label = convert_dict_list_strings(train['answers'].tolist())

In [ ]:
label[:5]

["['จุงลิ่ว': [2], 'แคส': [2,5]]",
 "['จิรศักก์': [1], 'ไขนภา': [1]]",
 "['คมกาญจน์': [2,4,5], 'จิรานุวัตร': [6]]",
 "['ขจรพงค์': [3]]",
 "['กิมใจ': [2,5,7], 'ขนิฐชีพ': [5]]"]

In [ ]:
train['label'] = label

In [ ]:
train.to_csv('train_each_label.csv', index=False)

# start fine tuning

In [ ]:
train = pd.read_csv('/content/train_each_label.csv')
train.head(2)

,id,story,answers,label
0,OhbVrpoiVg,จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้...,"[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]","['จุงลิ่ว': [2], 'แคส': [2,5]]"
1,RV5IfLBcbf,จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเด...,"[{'จิรศักก์': '[1]'}, {'ไขนภา': '[1]'}]","['จิรศักก์': [1], 'ไขนภา': [1]]"

In [ ]:
import ast
answers = train['answers'].tolist()
name = [[list(d.keys())[0] for d in ast.literal_eval(item)] for item in answers]
name = [str(m) for m in name]

In [ ]:
train['name'] = name

In [ ]:
train.head()

,id,story,answers,label,name
0,OhbVrpoiVg,จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้...,"[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]","['จุงลิ่ว': [2], 'แคส': [2,5]]","['จุงลิ่ว', 'แคส']"
1,RV5IfLBcbf,จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเด...,"[{'จิรศักก์': '[1]'}, {'ไขนภา': '[1]'}]","['จิรศักก์': [1], 'ไขนภา': [1]]","['จิรศักก์', 'ไขนภา']"
2,noGMbJmTPS,คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกร...,"[{'คมกาญจน์': '[2,4,5]'}, {'จิรานุวัตร': '[6]'}]","['คมกาญจน์': [2,4,5], 'จิรานุวัตร': [6]]","['คมกาญจน์', 'จิรานุวัตร']"
3,IAoCLrZ3aW,ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพ...,[{'ขจรพงค์': '[3]'}],['ขจรพงค์': [3]],['ขจรพงค์']
4,ZkSBvrjn9W,กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร...,"[{'กิมใจ': '[2,5,7]'}, {'ขนิฐชีพ': '[5]'}]","['กิมใจ': [2,5,7], 'ขนิฐชีพ': [5]]","['กิมใจ', 'ขนิฐชีพ']"

## prep data for fine tuning

In [ ]:
train.head()

,id,story,answers,label,name
0,OhbVrpoiVg,จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้...,"[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]","['จุงลิ่ว': [2], 'แคส': [2,5]]","['จุงลิ่ว', 'แคส']"
1,RV5IfLBcbf,จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเด...,"[{'จิรศักก์': '[1]'}, {'ไขนภา': '[1]'}]","['จิรศักก์': [1], 'ไขนภา': [1]]","['จิรศักก์', 'ไขนภา']"
2,noGMbJmTPS,คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกร...,"[{'คมกาญจน์': '[2,4,5]'}, {'จิรานุวัตร': '[6]'}]","['คมกาญจน์': [2,4,5], 'จิรานุวัตร': [6]]","['คมกาญจน์', 'จิรานุวัตร']"
3,IAoCLrZ3aW,ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพ...,[{'ขจรพงค์': '[3]'}],['ขจรพงค์': [3]],['ขจรพงค์']
4,ZkSBvrjn9W,กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร...,"[{'กิมใจ': '[2,5,7]'}, {'ขนิฐชีพ': '[5]'}]","['กิมใจ': [2,5,7], 'ขนิฐชีพ': [5]]","['กิมใจ', 'ขนิฐชีพ']"

In [ ]:
train['story'].tolist()[:10]

['จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้ปืนจี้ชิงเงินสดจากสถานีขนส่ง',
 'จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเดินตกบันไดด้วยความประมาทส่งผลให้ตนเองขาหัก',
 'คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกรุกเข้าหลังร้านเพื่อขโมยของ มีผลให้เกิดความเสียหายต่อทรัพย์สิน ขณะที่จิรานุวัตรฉ้อโกงผ่านโทรศัพท์',
 'ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพร้อมผู้โดยสาร',
 'กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร้านทอง และขโมยทองที่บรรทุกมา ส่วนขนิฐชีพทุบทำลายกล้องวงจรปิดด้วยความสะใจเฉยๆ',
 'ขวัญอรุณวางเพลิงอาคารเก่าทำให้ทรัพย์สินเสียหาย และลักทรัพย์ในห้องควบคุม',
 'จิรเวทพิมพ์ผิดรหัสฉุกเฉิน ทำให้ระบบแจ้งเตือนหยุดทำงาน',
 'กาญจน์อรยิงผู้รักษาความปลอดภัยจนเสียชีวิต ขณะที่ขวัญอมรลักบัตรผ่านเข้าออกอาคารและขโมยเอกสารภายใน',
 'กานดาศรีลอบบุกรุกเข้าห้องเก็บของในอาคารและขโมยโทรศัพท์ออกไปในคืนวันหยุด ขณะที่กิมหุนฉ้อโกงนักลงทุนด้วยเอกสารปลอม',
 'กฤติภรใช้มีดข่มขู่ในงานเลี้ยงโรงแรมและทำให้ฝ่ายที่เกี่ยวข้องบาดเจ็บอย่างรุนแรง ขณะที่จำเป็นศรีขโมยของจากตลาดนัดด้วยการบุกรุก']

In [ ]:
instruction = """
กรุณาวิเคราะห์ข้อความภาษาไทยต่อไปนี้อย่างละเอียด โดยจะกำหนดบุคคลทั้งหมดในข้อความนี้ให้
ซึ่งต้องแยกแยะบุคคลที่มีความผิดลักทรัพย์หรือชิงทรัพย์
1. ถ้าบุคคลในข้อความไม่มีความผิดอะไรเลย ให้แท็กเป็น 1
2. ถ้าบุคคลในข้อความ มีความผิดลักทรัพย์หรือชิงทรัพย์ให้แท็กเป็น 2
3. กระทํา การใดๆ ด้วยความ ประมาท, ละเลย หรือไม่ได้ตั้งใจส่งผลให้เกิดความเสียหายต่อชีวิตหรือทรัพย์สิน ให้แท็กเป็น 3 (เน้นการประมาท)
4. ถ้าบุคคลในข้อความบุกรุกเข้าเขตหวงห้ามหรือนอกเวลาทำการ ให้แท็กเป็น 4
5. ถ้าบุคคลในข้อความมีการกระทำใดๆด้ววยเจตนาที่ส่งผลให้เกิดความเสียหายทางด้านร่างกาย, จิตใจหรือทรัพย์สิน ให้แท็กเป็น 5 (เน้นการเจตนา)
6. ถ้าบุตตลในข้อความ มีความผิดฉ้อโกงประชาชน ปลอมแปลงเอกสาร หรือปลอมแปลงสิ่งของต่างๆเพื่อนำมาใช้ในเชิงการค้า ให้แท็กเป็น 6
7. ถ้าบุคคลในข้อความ ทำให้ผู้อื่นเสียชีวิตด้วยวิธีการใดก็ตาม ให้แท็กเป็น 7

กฎการแท็กเพิ่มเติม
 - สามารถมีหลายแท็กได้ในบุคคลเดียว
 - ให้ตอบเฉพาะชื่อบุคคลที่กำหนดให้เท่านั้น ห้ามเพิ่มชื่อ หรือตัดชื่อออก
 - การทำให้คนอื่นเสียชีวิตเกิดจากความตั้งใจ, ทะเลาะวิวาทหรือวิธีที่เหนือธรรมชาติจะแทนด้วย “5,7”
 - การทำให้คนอื่นเสียชีวิตเกิดจากความไม่ตั้งใจหรือความประมาทจะถือเป็น “3,7”
 - “7” ไม่มีทางเกิดขึ้นได้โดยไม่มี “3” หรือ “5”
 - การทำให้ตนเองเสียชีวิตไม่ถือว่ามีความผิด
 - การโจรกรรมหรือการบุกรุกใดๆ ที่เล่าถึงการมีทรัพย์สินเสียหายจะต้องมี “5” รวมอยู่ในนั้นด้วย
 - ถ้าไม่มีคำใดที่สื่อถึง “ความตาย”, “ฆ่า” หรือ “วางแผนฆ่า” จะถือว่าไม่มีการเสียชีวิต คือ จะไม่มีเลข 7
 - ถึงแม้จะไม่ได้กระทำความผิดใดๆ เลยก็ตาม แต่เนื้อเรื่องอยู่ในเรื่องราว จะถือว่าเป็น “1”
โดยให้ตอบในรูปแบบ
[ชื่อบุคคล1: แท็ก , ชื่อบุคคล2: แท็ก]

ตัวอย่าง1
ชื่อที่กำหนด : ['จุงลิ่ว', 'แคส']
ข้อความ : จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้ปืนจี้ชิงเงินสดจากสถานีขนส่ง
คำตอบที่ต้องการ: ['จุงลิ่ว': [2], 'แคส': [2,5]]

ตัวอย่าง2
ชื่อที่กำหนด : ['จิรศักก์', 'ไขนภา']
ข้อความ : จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเดินตกบันไดด้วยความประมาทส่งผลให้ตนเองขาหัก
คำตอบที่ต้องการ: ['จิรศักก์': [1], 'ไขนภา': [1]]

ตัวอย่าง3
ชื่อที่กำหนด : ['กิมใจ', 'ขนิฐชีพ']
ข้อความ : กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร้านทอง และขโมยทองที่บรรทุกมา ส่วนขนิฐชีพทุบทำลายกล้องวงจรปิดด้วยความสะใจเฉยๆ
คำตอบที่ต้องการ: ['กิมใจ': [2,5,7], 'ขนิฐชีพ': [5]]
"""

In [ ]:
train.head(1)

,id,story,answers,label,name
0,OhbVrpoiVg,จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้...,"[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]","['จุงลิ่ว': [2], 'แคส': [2,5]]","['จุงลิ่ว', 'แคส']"

In [ ]:
train['train_prompt'] = train.apply(
    lambda row: f"ชื่อที่กำหนด : {row['name']}\nข้อความ : {row['story']}\nคำตอบที่ต้องการ: ", axis=1
)

In [ ]:
df = pd.DataFrame()
df['input'] = train['train_prompt'].tolist()
df['output'] = train['label'].tolist()
df['instruction'] = instruction

In [ ]:
from datasets import Dataset
dataset = Dataset.from_pandas(df)
dataset

Dataset({
    features: ['input', 'output', 'instruction'],
    num_rows: 1800
})

## start train class 1

In [ ]:
%%capture
!pip install unsloth
# Also get the latest nightly Unsloth!
!pip uninstall unsloth -y && pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
    # Can select any from the below:
    # "unsloth/Qwen2.5-0.5B", "unsloth/Qwen2.5-1.5B", "unsloth/Qwen2.5-3B"
    # "unsloth/Qwen2.5-14B",  "unsloth/Qwen2.5-32B",  "unsloth/Qwen2.5-72B",
    # And also all Instruct versions and Math. Coding verisons!
    model_name = "unsloth/Qwen2.5-14B",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.5.3: Fast Qwen2 patching. Transformers: 4.51.3.
   \\   /|    NVIDIA L4. Num GPUs = 1. Max memory: 22.161 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 8.9. CUDA Toolkit: 12.6. Triton: 3.3.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors.index.json:   0%|          | 0.00/196k [00:00<?, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/2.12G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/172 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/4.72k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2025.5.3 patched 48 layers with 48 QKV layers, 48 O layers and 48 MLP layers.

In [ ]:
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

EOS_TOKEN = tokenizer.eos_token # Must add EOS_TOKEN
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    outputs      = examples["output"]
    texts = []
    for instruction, input, output in zip(instructions, inputs, outputs):
        # Must add EOS_TOKEN, otherwise your generation will go on forever!
        text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }
pass

from datasets import load_dataset
dataset = dataset.map(formatting_prompts_func, batched = True,)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        num_train_epochs = 2, # Set this for 1 full training run.
        # max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/1800 [00:00<?, ? examples/s]

/usr/local/lib/python3.11/dist-packages/datasets/table.py:1395: FutureWarning: promote has been superseded by promote_options='default'.
  """Create `ConcatenationTable` from list of tables.
/usr/local/lib/python3.11/dist-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by promote_options='default'.
  result: list[list[TableBlock]], blocks: list[list[TableBlock]]

In [ ]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,800 | Num Epochs = 2 | Total steps = 450
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 68,812,800/14,000,000,000 (0.49% trained)

Unsloth: Will smartly offload gradients to save VRAM!

## Load model 1

In [ ]:
#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
model.push_to_hub("Jamvess/classAll_model_14b", token = "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") # Online saving
tokenizer.push_to_hub("Jamvess/classAll_model_14b", token = "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") # Online saving

README.md:   0%|          | 0.00/592 [00:00<?, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/275M [00:00<?, ?B/s]

Saved model to https://huggingface.co/Jamvess/classAll_model_14b

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

## inference class 1

In [ ]:
submit = pd.read_csv('/content/submission.csv')
submit.head(1)

,id,story,answers
0,XwlpP5otmI,เคี้ยนแพ้หมากรุกเลยชักปืนขึ้นมายิงจราจนเสียชีวิต,"[{'เคี้ยน': '[5,7]'}, {'จรา': '[1]'}]"

In [ ]:
predicted_names = np.load('/content/predicted_names.npy')
predicted_names = predicted_names.tolist()

FileNotFoundError: [Errno 2] No such file or directory: '/content/predicted_names.npy'

In [ ]:
submit['name'] = predicted_names

In [ ]:
submit['train_prompt'] = submit.apply(
    lambda row: f"ชื่อที่กำหนด : {row['name']}\nข้อความ : {row['story']}\nคำตอบที่ต้องการ: ", axis=1
)

In [ ]:
submit.head(10)

In [ ]:
train_prompt = submit['train_prompt'].tolist()

In [ ]:
instruction = """
กรุณาวิเคราะห์ข้อความภาษาไทยต่อไปนี้อย่างละเอียด โดยจะกำหนดบุคคลทั้งหมดในข้อความนี้ให้
ซึ่งต้องแยกแยะบุคคลที่มีความผิดลักทรัพย์หรือชิงทรัพย์
1. ถ้าบุคคลในข้อความไม่มีความผิดอะไรเลย ให้แท็กเป็น 1
2. ถ้าบุคคลในข้อความ มีความผิดลักทรัพย์หรือชิงทรัพย์ให้แท็กเป็น 2
3. กระทํา การใดๆ ด้วยความ ประมาท, ละเลย หรือไม่ได้ตั้งใจส่งผลให้เกิดความเสียหายต่อชีวิตหรือทรัพย์สิน ให้แท็กเป็น 3 (เน้นการประมาท)
4. ถ้าบุคคลในข้อความบุกรุกเข้าเขตหวงห้ามหรือนอกเวลาทำการ ให้แท็กเป็น 4
5. ถ้าบุคคลในข้อความมีการกระทำใดๆด้ววยเจตนาที่ส่งผลให้เกิดความเสียหายทางด้านร่างกาย, จิตใจหรือทรัพย์สิน ให้แท็กเป็น 5 (เน้นการเจตนา)
6. ถ้าบุตตลในข้อความ มีความผิดฉ้อโกงประชาชน ปลอมแปลงเอกสาร หรือปลอมแปลงสิ่งของต่างๆเพื่อนำมาใช้ในเชิงการค้า ให้แท็กเป็น 6
7. ถ้าบุคคลในข้อความ ทำให้ผู้อื่นเสียชีวิตด้วยวิธีการใดก็ตาม ให้แท็กเป็น 7
 - สามารถมีหลายแท็กได้ในบุคคลเดียว
 - ให้ตอบเฉพาะชื่อบุคคลที่กำหนดให้เท่านั้น ห้ามเพิ่มชื่อ หรือตัดชื่อออก
 - การทำให้คนอื่นเสียชีวิตเกิดจากความตั้งใจ, ทะเลาะวิวาทหรือวิธีที่เหนือธรรมชาติจะแทนด้วย “5,7”
 - การทำให้คนอื่นเสียชีวิตเกิดจากความไม่ตั้งใจหรือความประมาทจะถือเป็น “3,7”
 - “7” ไม่มีทางเกิดขึ้นได้โดยไม่มี “3” หรือ “5”
 - การทำให้ตนเองเสียชีวิตไม่ถือว่ามีความผิด
 - การโจรกรรมหรือการบุกรุกใดๆ ที่เล่าถึงการมีทรัพย์สินเสียหายจะต้องมี “5” รวมอยู่ในนั้นด้วย
 - ถ้าไม่มีคำใดที่สื่อถึง “ความตาย”, “ฆ่า” หรือ “วางแผนฆ่า” จะถือว่าไม่มีการเสียชีวิต คือ จะไม่มีเลข 7
 - ถึงแม้จะไม่ได้กระทำความผิดใดๆ เลยก็ตาม แต่เนื้อเรื่องอยู่ในเรื่องราว จะถือว่าเป็น “1”
โดยให้ตอบในรูปแบบ
[ชื่อบุคคล1: แท็ก , ชื่อบุคคล2: แท็ก]

ตัวอย่าง1
ชื่อที่กำหนด : ['จุงลิ่ว', 'แคส']
ข้อความ : จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้ปืนจี้ชิงเงินสดจากสถานีขนส่ง
คำตอบที่ต้องการ: ['จุงลิ่ว': [2], 'แคส': [2,5]]

ตัวอย่าง2
ชื่อที่กำหนด : ['จิรศักก์', 'ไขนภา']
ข้อความ : จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเดินตกบันไดด้วยความประมาทส่งผลให้ตนเองขาหัก
คำตอบที่ต้องการ: ['จิรศักก์': [1], 'ไขนภา': [1]]

ตัวอย่าง3
ชื่อที่กำหนด : ['กิมใจ', 'ขนิฐชีพ']
ข้อความ : กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร้านทอง และขโมยทองที่บรรทุกมา ส่วนขนิฐชีพทุบทำลายกล้องวงจรปิดด้วยความสะใจเฉยๆ
คำตอบที่ต้องการ: ['กิมใจ': [2,5,7], 'ขนิฐชีพ': [5]]

*** กฏเด็ดขาด
ห้ามแท็กอย่างอื่น นอกจากเลข 1 - 7 และไม่ต้องแท็กเลขเดิมซ้ำสองครั้ง
กฎการแท็กเพิ่มเติม
***
"""

In [ ]:
# alpaca_prompt = Copied from above
FastLanguageModel.for_inference(model) # Enable native 2x faster inference
inputs = tokenizer(
[
    alpaca_prompt.format(
        instruction, # instruction
        train_prompt[58], # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True, temperature=0)
tokenizer.batch_decode(outputs)

In [ ]:
from tqdm import tqdm
import re
all_class_ans = []
for i in range(len(train_prompt)):
  inputs = tokenizer(
  [
      alpaca_prompt.format(
          instruction, # instruction
          train_prompt[i], # input
          "", # output - leave this blank for generation!
      )
  ], return_tensors = "pt").to("cuda")
  outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
  outputs = tokenizer.batch_decode(outputs)
  match = re.search(r"### Response:\s*(\[.*?\])<\|endoftext\|>", outputs[0] , re.DOTALL)
  if match:
    response = match.group(1)
  print(i, response)
  all_class_ans.append(response)

In [ ]:
np.save('all_class_ans.npy', all_class_ans)

In [ ]:
all_class_ans

In [ ]:
import numpy as np

# ABC

In [ ]:
all_class_ans = np.load('/content/all_class_ans.npy', allow_pickle=True)
all_class_ans = all_class_ans.tolist()

In [ ]:
all_class_ans

In [ ]:
import re

def fix_and_dedup_tags(entries):
    fixed = []
    for entry in entries:
        entry = entry.replace("'::", "':")
        matches = re.findall(r"'(.*?)'\s*:\s*\[(.*?)\]", entry)
        new_items = []
        for name, numbers in matches:
            num_list = []
            seen = set()
            for num in numbers.split(','):
                num = num.strip()
                if num.isdigit():
                    digits = [int(d) for d in str(num)] if int(num) > 9 else [int(num)]
                    for d in digits:
                        if d not in seen:
                            num_list.append(d)
                            seen.add(d)
            new_items.append(f"'{name}': {num_list}")
        fixed.append(f"[{', '.join(new_items)}]")
    return fixed

cleaned = fix_and_dedup_tags(all_class_ans)

In [ ]:
print(cleaned[:3])

In [ ]:
print(submit['answers'].tolist()[:3])

In [ ]:
import re
def format_entries(data):
    result = []
    for line in data:
        line = line.replace("'::", "':")  # fix malformed colon
        entries = re.findall(r"'(.*?)'\s*:\s*\[(.*?)\]", line)
        entry_list = []
        for name, nums in entries:
            flat_nums = []
            seen = set()
            for num in nums.split(','):
                num = num.strip()
                if num.isdigit():
                    digits = [int(d) for d in str(num)]
                    for d in digits:
                        if d not in seen:
                            flat_nums.append(d)
                            seen.add(d)
            entry_list.append({name: str(flat_nums).replace(" ", "")})
        result.append(str(entry_list).replace(" ", ""))
    return result

formatted_data = format_entries(cleaned)

In [ ]:
submit.head()

In [ ]:
submit['answers'] = formatted_data

In [ ]:
submit.to_csv('submission_Jam.csv', index=False)

# fix name again

In [ ]:
all_name_ans = np.load('/content/predicted_names.npy', allow_pickle=True)
all_name_ans = all_name_ans.tolist()

In [ ]:
print(all_name_ans)

In [ ]:
for item in all_name_ans[900:1000]:
  print(item)