# AutoGluon Tabular Forecasting

## Import Library

In [116]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# For time series
from typing import List

# from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import userdata

In [117]:
def download_kaggle(kaggle_command="kaggle competitions download -c liver-fibrosis-severity-prediction"):

  # Get Kaggle Key
  kaggle_username = userdata.get("KAGGLE_USER")
  kaggle_key = userdata.get("KAGGLE_KEY")
  if not kaggle_username or not kaggle_key:
      print("Error: Kaggle_USERNAME or Kaggle_KEY not found in Colab Secrets.")
      return

  # Write the credentials to ~/.kaggle/kaggle.json
  kaggle_dir = os.path.expanduser("~/.kaggle")
  os.makedirs(kaggle_dir, exist_ok=True)

  # Create JSON
  kaggle_json_path = os.path.join(kaggle_dir, "kaggle.json")
  with open(kaggle_json_path, "w") as f:
      f.write(f'{{"username":"{kaggle_username}","key":"{kaggle_key}"}}')
  os.chmod(kaggle_json_path, 0o600)

  try:
      os.system(kaggle_command)
      print("\n--- Download complete! ---")
      os.system("ls -la")
      os.system("unzip -o '*.zip' && rm -f *.zip")
      os.system("ls -la")

  except Exception as e:
      print(f"An error occurred during download: {e}")

In [118]:
download_kaggle(
    "kaggle competitions download -c individual-test-temperature-prediction"
)

--- Download complete! ---

## Explore Dataset

In [119]:
df_train = pd.read_csv("/content/IOT_Train.csv")
df_train

,mac,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,time,humid,light,pm10,pm2.5,rainfall,wind_direct,wind_speed,temp
0,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-20 15:00:00+07:00,70.6,59.0,NaN,NaN,0.0,45.0,4.3,32.6
1,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-16 09:00:00+07:00,62.3,76.0,NaN,NaN,0.0,45.0,1.9,37.9
2,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-06-26 19:00:00+07:00,90.3,0.0,NaN,NaN,0.0,135.0,3.2,26.4
3,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-16 04:00:00+07:00,91.7,0.0,NaN,NaN,0.0,157.5,0.0,25.6
4,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-30 08:00:00+07:00,59.1,71.0,NaN,NaN,0.0,180.0,2.3,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13630,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-06-14 01:00:00+07:00,97.9,0.0,NaN,NaN,4.2,0.0,0.0,23.5
13631,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-03 02:00:00+07:00,80.6,0.0,NaN,NaN,0.0,135.0,2.9,19.3
13632,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-19 06:00:00+07:00,87.9,37.0,NaN,NaN,0.0,45.0,3.0,24.5
13633,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-06-15 02:00:00+07:00,89.9,0.0,NaN,NaN,0.0,315.0,0.0,27.3
13634,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-06-05 18:00:00+07:00,66.3,43.0,NaN,NaN,0.0,45.0,0.8,33.5

In [120]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13635 entries, 0 to 13634
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   mac            13635 non-null  object
 1   station_name   13635 non-null  object
 2   tambon_code    13635 non-null  int64
 3   tambon_namt    13635 non-null  object
 4   amphur_code    13635 non-null  int64
 5   amphur_namt    13635 non-null  object
 6   province_code  13635 non-null  int64
 7   province_namt  13635 non-null  object
 8   latitude       13635 non-null  float64
 9   longitude      13635 non-null  float64
 10  time           13635 non-null  object
 11  humid          13635 non-null  float64
 12  light          13635 non-null  float64
 13  pm10           6841 non-null   float64
 14  pm2.5          6841 non-null   float64
 15  rainfall       13635 non-null  float64
 16  wind_direct    13635 non-null  float64
 17  wind_speed     13635 non-null  float64
 18  temp           13634 non-null  float64
dtypes: float64(10), int64(3), object(6)
memory usage: 2.0+ MB

In [121]:
print(len(df_train["mac"].unique()))
print(len(df_train["station_name"].unique()))

8
8

In [122]:
df_train["time"] = pd.to_datetime(df_train["time"])
df_train = df_train.sort_values(by="time")
df_train["time"]

6361    2022-05-02 00:00:00+07:00
8429    2022-05-02 00:00:00+07:00
1678    2022-05-02 00:00:00+07:00
11871   2022-05-02 00:00:00+07:00
13614   2022-05-02 00:00:00+07:00
                   ...
55      2022-07-31 21:00:00+07:00
10275   2022-07-31 21:00:00+07:00
1806    2022-07-31 21:00:00+07:00
8545    2022-07-31 21:00:00+07:00
6830    2022-07-31 21:00:00+07:00
Name: time, Length: 13635, dtype: datetime64[ns, UTC+07:00]

In [123]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13635 entries, 6361 to 6830
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   mac            13635 non-null  object
 1   station_name   13635 non-null  object
 2   tambon_code    13635 non-null  int64
 3   tambon_namt    13635 non-null  object
 4   amphur_code    13635 non-null  int64
 5   amphur_namt    13635 non-null  object
 6   province_code  13635 non-null  int64
 7   province_namt  13635 non-null  object
 8   latitude       13635 non-null  float64
 9   longitude      13635 non-null  float64
 10  time           13635 non-null  datetime64[ns, UTC+07:00]
 11  humid          13635 non-null  float64
 12  light          13635 non-null  float64
 13  pm10           6841 non-null   float64
 14  pm2.5          6841 non-null   float64
 15  rainfall       13635 non-null  float64
 16  wind_direct    13635 non-null  float64
 17  wind_speed     13635 non-null  float64
 18  temp           13634 non-null  float64
dtypes: datetime64[ns, UTC+07:00](1), float64(10), int64(3), object(5)
memory usage: 2.1+ MB

### Time Features

In [124]:
def extract_time_features(df: pd.DataFrame, time_columns: list = None) -> pd.DataFrame:
    """
    Extracts time-based features from specified columns in a DataFrame.
    If time_columns is not provided, it attempts to infer time columns
    by checking common time-related column names.

    Args:
        df (pd.DataFrame): The input DataFrame.
        time_columns (list, optional): A list of column names containing time data.
                                        If None, common time-related column names will be checked.

    Returns:
        pd.DataFrame: The DataFrame with new time feature columns.
    """

    df_copy = df.copy()

    # Common time-related column name patterns for inference
    if time_columns is None:
        possible_time_col_patterns = [
            'time', 'date', 'timestamp', 'datetime', 'created_at',
            'updated_at', 'ts', 'event_time', 'start_time', 'end_time'
        ]
        inferred_time_columns = [
            col for col in df_copy.columns
            if any(pattern in col.lower() for pattern in possible_time_col_patterns)
        ]
        if not inferred_time_columns:
            print("Warning: No time columns specified and no common time-related columns found. "
                  "Returning original DataFrame.")
            return df_copy
        time_columns = inferred_time_columns
        print(f"Inferred time columns: {time_columns}")

    # Possible time formats to try for robust parsing
    # Ordered from most specific/common to more general
    possible_time_formats = [
        "%Y-%m-%d %H:%M:%S.%f",  # 2025-07-05 13:42:29.123456
        "%Y-%m-%d %H:%M:%S",    # 2025-07-05 13:42:29
        "%Y-%m-%dT%H:%M:%S.%fZ",# ISO 8601 with Z (UTC)
        "%Y-%m-%dT%H:%M:%S",    # ISO 8601 without Z
        "%Y/%m/%d %H:%M:%S",    # 2025/07/05 13:42:29
        "%d-%m-%Y %H:%M:%S",    # 05-07-2025 13:42:29
        "%m/%d/%Y %I:%M:%S %p", # 07/05/2025 01:42:29 PM
        "%d/%m/%Y %H:%M",       # 05/07/2025 13:42
        "%Y-%m-%d",             # 2025-07-05
        "%d-%m-%Y",             # 05-07-2025
        "%m/%d/%Y",             # 07/05/2025
        "%H:%M:%S",             # 13:42:29
        "%H:%M",                # 13:42
        "%I:%M %p"              # 01:42 PM
    ]

    for col in time_columns:
        if col not in df_copy.columns:
            print(f"Warning: Column '{col}' not found in DataFrame. Skipping.")
            continue

        # Convert to datetime, coercing errors to NaT (Not a Time)
        # We try multiple formats with errors='coerce' to handle mixed formats
        df_copy[f'{col}_dt'] = pd.to_datetime(df_copy[col], errors='coerce', infer_datetime_format=True)

        # Drop rows where conversion failed for this column, or handle as NaT
        # For simplicity in feature extraction, we'll proceed with NaT values
        # If a column is entirely NaT after conversion, it's probably not a time column
        if df_copy[f'{col}_dt'].isnull().all() and not df_copy[col].isnull().all():
            print(f"Warning: Column '{col}' could not be converted to datetime. Skipping feature extraction for this column.")
            df_copy = df_copy.drop(columns=[f'{col}_dt'])
            continue

        # Extract features
        dt_col = df_copy[f'{col}_dt'].dt
        df_copy[f'{col}_year'] = dt_col.year
        df_copy[f'{col}_month'] = dt_col.month
        df_copy[f'{col}_day'] = dt_col.day
        df_copy[f'{col}_hour'] = dt_col.hour
        df_copy[f'{col}_minute'] = dt_col.minute
        df_copy[f'{col}_second'] = dt_col.second
        df_copy[f'{col}_dayofweek'] = dt_col.dayofweek # Monday=0, Sunday=6
        df_copy[f'{col}_dayofyear'] = dt_col.dayofyear
        df_copy[f'{col}_weekofyear'] = dt_col.isocalendar().week.astype(int)
        df_copy[f'{col}_quarter'] = dt_col.quarter
        df_copy[f'{col}_is_weekend'] = dt_col.dayofweek.isin([5, 6]).astype(int)
        df_copy[f'{col}_season'] = (dt_col.month % 12 + 3) // 3 # Simple season mapping
        df_copy[f'{col}_is_month_start'] = dt_col.is_month_start.astype(int)
        df_copy[f'{col}_is_month_end'] = dt_col.is_month_end.astype(int)
        df_copy[f'{col}_is_quarter_start'] = dt_col.is_quarter_start.astype(int)
        df_copy[f'{col}_is_quarter_end'] = dt_col.is_quarter_end.astype(int)
        df_copy[f'{col}_is_year_start'] = dt_col.is_year_start.astype(int)
        df_copy[f'{col}_is_year_end'] = dt_col.is_year_end.astype(int)

        # Optional: Add cyclical features (sin/cos transformations for hour, dayofweek, etc.)
        # These are useful for models to understand cyclical patterns without arbitrary breaks
        # Example for hour
        df_copy[f'{col}_hour_sin'] = np.sin(2 * np.pi * dt_col.hour / 24)
        df_copy[f'{col}_hour_cos'] = np.cos(2 * np.pi * dt_col.hour / 24)

    return df_copy

In [125]:
df_train = extract_time_features(df=df_train, time_columns=["time"])
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13635 entries, 6361 to 6830
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   mac                    13635 non-null  object
 1   station_name           13635 non-null  object
 2   tambon_code            13635 non-null  int64
 3   tambon_namt            13635 non-null  object
 4   amphur_code            13635 non-null  int64
 5   amphur_namt            13635 non-null  object
 6   province_code          13635 non-null  int64
 7   province_namt          13635 non-null  object
 8   latitude               13635 non-null  float64
 9   longitude              13635 non-null  float64
 10  time                   13635 non-null  datetime64[ns, UTC+07:00]
 11  humid                  13635 non-null  float64
 12  light                  13635 non-null  float64
 13  pm10                   6841 non-null   float64
 14  pm2.5                  6841 non-null   float64
 15  rainfall               13635 non-null  float64
 16  wind_direct            13635 non-null  float64
 17  wind_speed             13635 non-null  float64
 18  temp                   13634 non-null  float64
 19  time_dt                13635 non-null  datetime64[ns, UTC+07:00]
 20  time_year              13635 non-null  int32
 21  time_month             13635 non-null  int32
 22  time_day               13635 non-null  int32
 23  time_hour              13635 non-null  int32
 24  time_minute            13635 non-null  int32
 25  time_second            13635 non-null  int32
 26  time_dayofweek         13635 non-null  int32
 27  time_dayofyear         13635 non-null  int32
 28  time_weekofyear        13635 non-null  int64
 29  time_quarter           13635 non-null  int32
 30  time_is_weekend        13635 non-null  int64
 31  time_season            13635 non-null  int32
 32  time_is_month_start    13635 non-null  int64
 33  time_is_month_end      13635 non-null  int64
 34  time_is_quarter_start  13635 non-null  int64
 35  time_is_quarter_end    13635 non-null  int64
 36  time_is_year_start     13635 non-null  int64
 37  time_is_year_end       13635 non-null  int64
 38  time_hour_sin          13635 non-null  float64
 39  time_hour_cos          13635 non-null  float64
dtypes: datetime64[ns, UTC+07:00](2), float64(12), int32(10), int64(11), object(5)
memory usage: 3.7+ MB

/tmp/ipython-input-124-1301132536.py:61: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df_copy[f'{col}_dt'] = pd.to_datetime(df_copy[col], errors='coerce', infer_datetime_format=True)

In [126]:
df_train = df_train.drop(columns=["time_dt", "mac"])
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13635 entries, 6361 to 6830
Data columns (total 38 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   station_name           13635 non-null  object
 1   tambon_code            13635 non-null  int64
 2   tambon_namt            13635 non-null  object
 3   amphur_code            13635 non-null  int64
 4   amphur_namt            13635 non-null  object
 5   province_code          13635 non-null  int64
 6   province_namt          13635 non-null  object
 7   latitude               13635 non-null  float64
 8   longitude              13635 non-null  float64
 9   time                   13635 non-null  datetime64[ns, UTC+07:00]
 10  humid                  13635 non-null  float64
 11  light                  13635 non-null  float64
 12  pm10                   6841 non-null   float64
 13  pm2.5                  6841 non-null   float64
 14  rainfall               13635 non-null  float64
 15  wind_direct            13635 non-null  float64
 16  wind_speed             13635 non-null  float64
 17  temp                   13634 non-null  float64
 18  time_year              13635 non-null  int32
 19  time_month             13635 non-null  int32
 20  time_day               13635 non-null  int32
 21  time_hour              13635 non-null  int32
 22  time_minute            13635 non-null  int32
 23  time_second            13635 non-null  int32
 24  time_dayofweek         13635 non-null  int32
 25  time_dayofyear         13635 non-null  int32
 26  time_weekofyear        13635 non-null  int64
 27  time_quarter           13635 non-null  int32
 28  time_is_weekend        13635 non-null  int64
 29  time_season            13635 non-null  int32
 30  time_is_month_start    13635 non-null  int64
 31  time_is_month_end      13635 non-null  int64
 32  time_is_quarter_start  13635 non-null  int64
 33  time_is_quarter_end    13635 non-null  int64
 34  time_is_year_start     13635 non-null  int64
 35  time_is_year_end       13635 non-null  int64
 36  time_hour_sin          13635 non-null  float64
 37  time_hour_cos          13635 non-null  float64
dtypes: datetime64[ns, UTC+07:00](1), float64(12), int32(10), int64(11), object(4)
memory usage: 3.5+ MB

In [127]:
# df_train = df_train.drop(columns=["time"])
# df_train.info()

In [128]:
print(df_train["station_name"].unique())
print(df_train["tambon_namt"].unique())
print(df_train["province_namt"].unique())

['โรงเรียนท่าข้ามวิทยา' 'โรงเรียนบ้านนา' 'บ้านนา_2'
 'โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)' 'โรงเรียนหนองสูงสามัคคีวิทยา_2'
 'บ้านนาสะแบง_2' 'บ้านสำโรงเกียรติ_2' 'โรงเรียนสรรพวิทยาคม']
['ท่าข้าม' 'สถาน' 'กำปัง' 'ดินแดง' 'หนองสูงเหนือ' 'นาสะแบง' 'บักดอง'
 'แม่สอด']
['ชุมพร' 'น่าน' 'นครราชสีมา' 'กรุงเทพมหานคร' 'มุกดาหาร' 'บึงกาฬ'
 'ศรีสะเกษ' 'ตาก']

In [129]:
df_train

,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,time,...,time_is_weekend,time_season,time_is_month_start,time_is_month_end,time_is_quarter_start,time_is_quarter_end,time_is_year_start,time_is_year_end,time_hour_sin,time_hour_cos
6361,โรงเรียนท่าข้ามวิทยา,860206,ท่าข้าม,8602,ท่าแซะ,86,ชุมพร,10.579849,99.113146,2022-05-02 00:00:00+07:00,...,0,2,0,0,0,0,0,0,0.000000,1.000000
8429,โรงเรียนบ้านนา,550404,สถาน,5504,นาน้อย,55,น่าน,18.241106,100.690577,2022-05-02 00:00:00+07:00,...,0,2,0,0,0,0,0,0,0.000000,1.000000
1678,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-02 00:00:00+07:00,...,0,2,0,0,0,0,0,0,0.000000,1.000000
11871,โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล),102601,ดินแดง,1026,ดินแดง,10,กรุงเทพมหานคร,13.777972,100.569662,2022-05-02 00:00:00+07:00,...,0,2,0,0,0,0,0,0,0.000000,1.000000
13614,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-02 00:00:00+07:00,...,0,2,0,0,0,0,0,0,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-31 21:00:00+07:00,...,1,3,0,1,0,0,0,0,-0.707107,0.707107
10275,โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล),102601,ดินแดง,1026,ดินแดง,10,กรุงเทพมหานคร,13.777972,100.569662,2022-07-31 21:00:00+07:00,...,1,3,0,1,0,0,0,0,-0.707107,0.707107
1806,บ้านนาสะแบง_2,380704,นาสะแบง,3807,ศรีวิไล,38,บึงกาฬ,18.142499,103.806521,2022-07-31 21:00:00+07:00,...,1,3,0,1,0,0,0,0,-0.707107,0.707107
8545,โรงเรียนสรรพวิทยาคม,630601,แม่สอด,6306,แม่สอด,63,ตาก,16.712990,98.573417,2022-07-31 21:00:00+07:00,...,1,3,0,1,0,0,0,0,-0.707107,0.707107
6830,โรงเรียนบ้านนา,550404,สถาน,5504,นาน้อย,55,น่าน,18.241106,100.690577,2022-07-31 21:00:00+07:00,...,1,3,0,1,0,0,0,0,-0.707107,0.707107

In [130]:
df_train = df_train.drop(columns=[
    "time_year", "time_is_year_start", "time_is_year_end"
])

df_train

,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,time,...,time_weekofyear,time_quarter,time_is_weekend,time_season,time_is_month_start,time_is_month_end,time_is_quarter_start,time_is_quarter_end,time_hour_sin,time_hour_cos
6361,โรงเรียนท่าข้ามวิทยา,860206,ท่าข้าม,8602,ท่าแซะ,86,ชุมพร,10.579849,99.113146,2022-05-02 00:00:00+07:00,...,18,2,0,2,0,0,0,0,0.000000,1.000000
8429,โรงเรียนบ้านนา,550404,สถาน,5504,นาน้อย,55,น่าน,18.241106,100.690577,2022-05-02 00:00:00+07:00,...,18,2,0,2,0,0,0,0,0.000000,1.000000
1678,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-02 00:00:00+07:00,...,18,2,0,2,0,0,0,0,0.000000,1.000000
11871,โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล),102601,ดินแดง,1026,ดินแดง,10,กรุงเทพมหานคร,13.777972,100.569662,2022-05-02 00:00:00+07:00,...,18,2,0,2,0,0,0,0,0.000000,1.000000
13614,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-02 00:00:00+07:00,...,18,2,0,2,0,0,0,0,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-31 21:00:00+07:00,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
10275,โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล),102601,ดินแดง,1026,ดินแดง,10,กรุงเทพมหานคร,13.777972,100.569662,2022-07-31 21:00:00+07:00,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
1806,บ้านนาสะแบง_2,380704,นาสะแบง,3807,ศรีวิไล,38,บึงกาฬ,18.142499,103.806521,2022-07-31 21:00:00+07:00,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
8545,โรงเรียนสรรพวิทยาคม,630601,แม่สอด,6306,แม่สอด,63,ตาก,16.712990,98.573417,2022-07-31 21:00:00+07:00,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
6830,โรงเรียนบ้านนา,550404,สถาน,5504,นาน้อย,55,น่าน,18.241106,100.690577,2022-07-31 21:00:00+07:00,...,30,3,1,3,0,1,0,0,-0.707107,0.707107

In [131]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13635 entries, 6361 to 6830
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   station_name           13635 non-null  object
 1   tambon_code            13635 non-null  int64
 2   tambon_namt            13635 non-null  object
 3   amphur_code            13635 non-null  int64
 4   amphur_namt            13635 non-null  object
 5   province_code          13635 non-null  int64
 6   province_namt          13635 non-null  object
 7   latitude               13635 non-null  float64
 8   longitude              13635 non-null  float64
 9   time                   13635 non-null  datetime64[ns, UTC+07:00]
 10  humid                  13635 non-null  float64
 11  light                  13635 non-null  float64
 12  pm10                   6841 non-null   float64
 13  pm2.5                  6841 non-null   float64
 14  rainfall               13635 non-null  float64
 15  wind_direct            13635 non-null  float64
 16  wind_speed             13635 non-null  float64
 17  temp                   13634 non-null  float64
 18  time_month             13635 non-null  int32
 19  time_day               13635 non-null  int32
 20  time_hour              13635 non-null  int32
 21  time_minute            13635 non-null  int32
 22  time_second            13635 non-null  int32
 23  time_dayofweek         13635 non-null  int32
 24  time_dayofyear         13635 non-null  int32
 25  time_weekofyear        13635 non-null  int64
 26  time_quarter           13635 non-null  int32
 27  time_is_weekend        13635 non-null  int64
 28  time_season            13635 non-null  int32
 29  time_is_month_start    13635 non-null  int64
 30  time_is_month_end      13635 non-null  int64
 31  time_is_quarter_start  13635 non-null  int64
 32  time_is_quarter_end    13635 non-null  int64
 33  time_hour_sin          13635 non-null  float64
 34  time_hour_cos          13635 non-null  float64
dtypes: datetime64[ns, UTC+07:00](1), float64(12), int32(9), int64(9), object(4)
memory usage: 3.3+ MB

In [132]:
df_train.columns

Index(['station_name', 'tambon_code', 'tambon_namt', 'amphur_code',
       'amphur_namt', 'province_code', 'province_namt', 'latitude',
       'longitude', 'time', 'humid', 'light', 'pm10', 'pm2.5', 'rainfall',
       'wind_direct', 'wind_speed', 'temp', 'time_month', 'time_day',
       'time_hour', 'time_minute', 'time_second', 'time_dayofweek',
       'time_dayofyear', 'time_weekofyear', 'time_quarter', 'time_is_weekend',
       'time_season', 'time_is_month_start', 'time_is_month_end',
       'time_is_quarter_start', 'time_is_quarter_end', 'time_hour_sin',
       'time_hour_cos'],
      dtype='object')

In [133]:
df_train = df_train.reset_index()

## Time Series Features

In [134]:
def time_series_features_rolling(df: pd.DataFrame,
                                 list_features_target_cols: list[str],
                                 list_window_size : list[int],
                                 list_aggregrate_function : list[str]):
  """
  Time Series Features Rolling :
  input ->
  - df
  - features_target_cols : list of target columns
  - window_size : window size for rolling calculations (e.g., [7, 30] for 7-day and 30-day windows).
  - aggregate_function : list of aggregate functions includes ['mean', 'std', 'min', 'max', 'median']
  return df with lagged features (nan will not be removed, please used df.dropna() after)
  """
  df_copy = df.copy()

  for feature_col in list_features_target_cols:
    for window in list_window_size:
      for agg_function in list_aggregrate_function:
        df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)

  return df_copy

In [135]:
def time_series_features_differencing(df: pd.DataFrame,
                                      list_features_target_cols: list[str],
                                      list_interval: list[int]):
  """
  Time Series Features Differencing:
  input ->
  - df (pd.DataFrame): The input DataFrame. It should have a DatetimeIndex for proper time-series operations,
                        though pandas' .diff() works on numerical indices too.
  - list_features_target_cols (List[str]): List of column names on which to apply differencing.
  - list_interval (List[int]): List of intervals (periods) for differencing (e.g., [1, 7, 12]).

  return ->
  pd.DataFrame: A new DataFrame with the added differenced features.
                NaN values will be present at the beginning of the series due to differencing.
                Please use df.dropna() after this operation if needed.
  """
  df_copy = df.copy()

  for feature_col in list_features_target_cols:
      for interval in list_interval:
          df_copy[f'{feature_col}_diff_{interval}'] = df_copy[feature_col].diff(periods=interval)

  return df_copy

In [136]:
def timeseries_features_lag(df: pd.DataFrame,
                            list_features_target_cols: list[str],
                            list_lags: list[int]):
  """
  Time Series Features Lagging :
  input -> df and list of target columns
  return df with lagged features (nan will not be removed, please used df.dropna() after)
  """
  df_copy = df.copy()

  for feature_col in list_features_target_cols:
    for lag in list_lags:
      df_copy[f'lag_{feature_col}_{lag}'] = df_copy[feature_col].shift(lag)

  return df_copy

In [137]:
df_train["tambon_code"].unique()

array([860206, 550404, 300903, 102601, 490706, 380704, 330802, 630601])

In [138]:
df_train

,index,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,...,time_weekofyear,time_quarter,time_is_weekend,time_season,time_is_month_start,time_is_month_end,time_is_quarter_start,time_is_quarter_end,time_hour_sin,time_hour_cos
0,6361,โรงเรียนท่าข้ามวิทยา,860206,ท่าข้าม,8602,ท่าแซะ,86,ชุมพร,10.579849,99.113146,...,18,2,0,2,0,0,0,0,0.000000,1.000000
1,8429,โรงเรียนบ้านนา,550404,สถาน,5504,นาน้อย,55,น่าน,18.241106,100.690577,...,18,2,0,2,0,0,0,0,0.000000,1.000000
2,1678,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,...,18,2,0,2,0,0,0,0,0.000000,1.000000
3,11871,โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล),102601,ดินแดง,1026,ดินแดง,10,กรุงเทพมหานคร,13.777972,100.569662,...,18,2,0,2,0,0,0,0,0.000000,1.000000
4,13614,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,...,18,2,0,2,0,0,0,0,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13630,55,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
13631,10275,โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล),102601,ดินแดง,1026,ดินแดง,10,กรุงเทพมหานคร,13.777972,100.569662,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
13632,1806,บ้านนาสะแบง_2,380704,นาสะแบง,3807,ศรีวิไล,38,บึงกาฬ,18.142499,103.806521,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
13633,8545,โรงเรียนสรรพวิทยาคม,630601,แม่สอด,6306,แม่สอด,63,ตาก,16.712990,98.573417,...,30,3,1,3,0,1,0,0,-0.707107,0.707107
13634,6830,โรงเรียนบ้านนา,550404,สถาน,5504,นาน้อย,55,น่าน,18.241106,100.690577,...,30,3,1,3,0,1,0,0,-0.707107,0.707107

In [139]:
list_tambon = [860206, 550404, 300903, 102601, 490706, 380704, 330802, 630601]

for tambon in list_tambon:

  print(df_train[ df_train["tambon_code"] == tambon ])

  # Get the unique tambon
  df = df_train[ df_train["tambon_code"] == tambon ]
  df = df.sort_values(by="time")

  # Apply Time Series Function
  df = time_series_features_rolling(
      df=df,
      list_features_target_cols=["pm10", "pm2.5", "rainfall", "wind_speed", "light"],
      list_window_size=[1, 3, 7, 15, 30],
      list_aggregrate_function=['mean', 'std', 'min', 'max', 'median']
  )

  df = timeseries_features_lag(
      df=df,
      list_features_target_cols=["pm10", "pm2.5", "rainfall", "wind_speed", "light"],
      list_lags=[1, 3, 7, 15, 30],
  )

  df = time_series_features_differencing(
      df=df,
      list_features_target_cols=["pm10", "pm2.5", "rainfall", "wind_speed", "light"],
      list_interval=[1, 3, 7, 15, 30],
  )

  # df_train = pd.merge(
  #     df_train,
  #     df,
  #     on = "index",
  #     how="left"
  # )

       index          station_name  tambon_code tambon_namt  amphur_code  \
0       6361  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
9       6641  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
16      5392  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
20      6680  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
28      5700  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
...      ...                   ...          ...         ...          ...
13595   5132  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
13602   5844  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
13609   6604  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
13616   6683  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602
13624   6345  โรงเรียนท่าข้ามวิทยา       860206     ท่าข้าม         8602

      amphur_namt  province_code province_namt   latitude  longitude  ...  \
0          ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
9          ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
16         ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
20         ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
28         ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
...           ...            ...           ...        ...        ...  ...
13595      ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
13602      ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
13609      ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
13616      ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...
13624      ท่าแซะ             86         ชุมพร  10.579849  99.113146  ...

      time_weekofyear  time_quarter  time_is_weekend  time_season  \
0                  18             2                0            2
9                  18             2                0            2
16                 18             2                0            2
20                 18             2                0            2
28                 18             2                0            2
...               ...           ...              ...          ...
13595              30             3                1            3
13602              30             3                1            3
13609              30             3                1            3
13616              30             3                1            3
13624              30             3                1            3

       time_is_month_start  time_is_month_end  time_is_quarter_start  \
0                        0                  0                      0
9                        0                  0                      0
16                       0                  0                      0
20                       0                  0                      0
28                       0                  0                      0
...                    ...                ...                    ...
13595                    0                  1                      0
13602                    0                  1                      0
13609                    0                  1                      0
13616                    0                  1                      0
13624                    0                  1                      0

       time_is_quarter_end  time_hour_sin  time_hour_cos
0                        0       0.000000   1.000000e+00
9                        0       0.258819   9.659258e-01
16                       0       0.500000   8.660254e-01
20                       0       0.707107   7.071068e-01
28                       0       0.866025   5.000000e-01
...                    ...            ...            ...
13595                    0      -0.866025  -5.000000e-01
13602                    0      -0.965926  -2.588190e-01
13609                    0      -1.000000  -1.836970e-16
13616                    0      -0.965926   2.588190e-01
13624                    0      -0.866025   5.000000e-01

[1600 rows x 36 columns]
       index    station_name  tambon_code tambon_namt  amphur_code  \
1       8429  โรงเรียนบ้านนา       550404        สถาน         5504
10      7674  โรงเรียนบ้านนา       550404        สถาน         5504
21      7204  โรงเรียนบ้านนา       550404        สถาน         5504
29      6858  โรงเรียนบ้านนา       550404        สถาน         5504
42      7906  โรงเรียนบ้านนา       550404        สถาน         5504
...      ...             ...          ...         ...          ...
13599   7571  โรงเรียนบ้านนา       550404        สถาน         5504
13604   8382  โรงเรียนบ้านนา       550404        สถาน         5504
13618   7382  โรงเรียนบ้านนา       550404        สถาน         5504
13620   8142  โรงเรียนบ้านนา       550404        สถาน         5504
13634   6830  โรงเรียนบ้านนา       550404        สถาน         5504

      amphur_namt  province_code province_namt   latitude   longitude  ...  \
1          นาน้อย             55          น่าน  18.241106  100.690577  ...
10         นาน้อย             55          น่าน  18.241106  100.690577  ...
21         นาน้อย             55          น่าน  18.241106  100.690577  ...
29         นาน้อย             55          น่าน  18.241106  100.690577  ...
42         นาน้อย             55          น่าน  18.241106  100.690577  ...
...           ...            ...           ...        ...         ...  ...
13599      นาน้อย             55          น่าน  18.241106  100.690577  ...
13604      นาน้อย             55          น่าน  18.241106  100.690577  ...
13618      นาน้อย             55          น่าน  18.241106  100.690577  ...
13620      นาน้อย             55          น่าน  18.241106  100.690577  ...
13634      นาน้อย             55          น่าน  18.241106  100.690577  ...

      time_weekofyear  time_quarter  time_is_weekend  time_season  \
1                  18             2                0            2
10                 18             2                0            2
21                 18             2                0            2
29                 18             2                0            2
42                 18             2                0            2
...               ...           ...              ...          ...
13599              30             3                1            3
13604              30             3                1            3
13618              30             3                1            3
13620              30             3                1            3
13634              30             3                1            3

       time_is_month_start  time_is_month_end  time_is_quarter_start  \
1                        0                  0                      0
10                       0                  0                      0
21                       0                  0                      0
29                       0                  0                      0
42                       0                  0                      0
...                    ...                ...                    ...
13599                    0                  1                      0
13604                    0                  1                      0
13618                    0                  1                      0
13620                    0                  1                      0
13634                    0                  1                      0

       time_is_quarter_end  time_hour_sin  time_hour_cos
1                        0       0.000000   1.000000e+00
10                       0       0.500000   8.660254e-01
21                       0       0.707107   7.071068e-01
29                       0       0.866025   5.000000e-01
42                       0       1.000000   6.123234e-17
...                    ...            ...            ...
13599                    0      -0.965926  -2.588190e-01
13604                    0      -1.000000  -1.836970e-16
13618                    0      -0.965926   2.588190e-01
13620                    0      -0.866025   5.000000e-01
13634                    0      -0.707107   7.071068e-01

[1732 rows x 36 columns]
       index station_name  tambon_code tambon_namt  amphur_code amphur_namt  \
2       1678     บ้านนา_2       300903       กำปัง         3009      โนนไทย
12       105     บ้านนา_2       300903       กำปัง         3009      โนนไทย
22       278     บ้านนา_2       300903       กำปัง         3009      โนนไทย
27       147     บ้านนา_2       300903       กำปัง         3009      โนนไทย
34       289     บ้านนา_2       300903       กำปัง         3009      โนนไทย
...      ...          ...          ...         ...          ...         ...
13597    807     บ้านนา_2       300903       กำปัง         3009      โนนไทย
13608   1632     บ้านนา_2       300903       กำปัง         3009      โนนไทย
13614    626     บ้านนา_2       300903       กำปัง         3009      โนนไทย
13626   1359     บ้านนา_2       300903       กำปัง         3009      โนนไทย
13630     55     บ้านนา_2       300903       กำปัง         3009      โนนไทย

       province_code province_namt   latitude   longitude  ...  \
2                 30    นครราชสีมา  15.112831  102.052114  ...
12                30    นครราชสีมา  15.112831  102.052114  ...
22                30    นครราชสีมา  15.112831  102.052114  ...
27                30    นครราชสีมา  15.112831  102.052114  ...
34                30    นครราชสีมา  15.112831  102.052114  ...
...              ...           ...        ...         ...  ...
13597             30    นครราชสีมา  15.112831  102.052114  ...
13608             30    นครราชสีมา  15.112831  102.052114  ...
13614             30    นครราชสีมา  15.112831  102.052114  ...
13626             30    นครราชสีมา  15.112831  102.052114  ...
13630             30    นครราชสีมา  15.112831  102.052114  ...

      time_weekofyear  time_quarter  time_is_weekend  time_season  \
2                  18             2                0            2
12                 18             2                0            2
22                 18             2                0            2
27                 18             2                0            2
34                 18             2                0            2
...               ...           ...              ...          ...
13597              30             3                1            3
13608              30             3                1            3
13614              30             3                1            3
13626              30             3                1            3
13630              30             3                1            3

       time_is_month_start  time_is_month_end  time_is_quarter_start  \
2                        0                  0                      0
12                       0                  0                      0
22                       0                  0                      0
27                       0                  0                      0
34                       0                  0                      0
...                    ...                ...                    ...
13597                    0                  1                      0
13608                    0                  1                      0
13614                    0                  1                      0
13626                    0                  1                      0
13630                    0                  1                      0

       time_is_quarter_end  time_hour_sin  time_hour_cos
2                        0       0.000000   1.000000e+00
12                       0       0.500000   8.660254e-01
22                       0       0.707107   7.071068e-01
27                       0       0.866025   5.000000e-01
34                       0       0.965926   2.588190e-01
...                    ...            ...            ...
13597                    0      -0.965926  -2.588190e-01
13608                    0      -1.000000  -1.836970e-16
13614                    0      -0.965926   2.588190e-01
13626                    0      -0.866025   5.000000e-01
13630                    0      -0.707107   7.071068e-01

[1697 rows x 36 columns]

/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)

       index                          station_name  tambon_code tambon_namt  \
3      11871  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
14     10553  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
19     10659  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
24     11887  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
40     11120  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
...      ...                                   ...          ...         ...
13601  11017  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
13605  11824  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
13619  10828  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
13627  11585  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง
13631  10275  โรงเรียนสามเสนนอก(ประชาราษฎร์อนุกูล)       102601      ดินแดง

       amphur_code amphur_namt  province_code  province_namt   latitude  \
3             1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
14            1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
19            1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
24            1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
40            1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
...            ...         ...            ...            ...        ...
13601         1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
13605         1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
13619         1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
13627         1026      ดินแดง             10  กรุงเทพมหานคร  13.777972
13631         1026      ดินแดง             10  กรุงเทพมหานคร  13.777972

        longitude  ... time_weekofyear  time_quarter  time_is_weekend  \
3      100.569662  ...              18             2                0
14     100.569662  ...              18             2                0
19     100.569662  ...              18             2                0
24     100.569662  ...              18             2                0
40     100.569662  ...              18             2                0
...           ...  ...             ...           ...              ...
13601  100.569662  ...              30             3                1
13605  100.569662  ...              30             3                1
13619  100.569662  ...              30             3                1
13627  100.569662  ...              30             3                1
13631  100.569662  ...              30             3                1

       time_season  time_is_month_start  time_is_month_end  \
3                2                    0                  0
14               2                    0                  0
19               2                    0                  0
24               2                    0                  0
40               2                    0                  0
...            ...                  ...                ...
13601            3                    0                  1
13605            3                    0                  1
13619            3                    0                  1
13627            3                    0                  1
13631            3                    0                  1

       time_is_quarter_start  time_is_quarter_end  time_hour_sin  \
3                          0                    0       0.000000
14                         0                    0       0.500000
19                         0                    0       0.707107
24                         0                    0       0.866025
40                         0                    0       1.000000
...                      ...                  ...            ...
13601                      0                    0      -0.965926
13605                      0                    0      -1.000000
13619                      0                    0      -0.965926
13627                      0                    0      -0.866025
13631                      0                    0      -0.707107

       time_hour_cos
3       1.000000e+00
14      8.660254e-01
19      7.071068e-01
24      5.000000e-01
40      6.123234e-17
...              ...
13601  -2.588190e-01
13605  -1.836970e-16
13619   2.588190e-01
13627   5.000000e-01
13631   7.071068e-01

[1727 rows x 36 columns]
       index                   station_name  tambon_code   tambon_namt  \
4      13614  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
18     12901  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
26     12600  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
30     12919  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
35     12459  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
...      ...                            ...          ...           ...
13600  12755  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
13607  13567  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
13617  12565  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
13625  13336  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ
13629  12017  โรงเรียนหนองสูงสามัคคีวิทยา_2       490706  หนองสูงเหนือ

       amphur_code amphur_namt  province_code province_namt   latitude  \
4             4907     หนองสูง             49      มุกดาหาร  16.494229
18            4907     หนองสูง             49      มุกดาหาร  16.494229
26            4907     หนองสูง             49      มุกดาหาร  16.494229
30            4907     หนองสูง             49      มุกดาหาร  16.494229
35            4907     หนองสูง             49      มุกดาหาร  16.494229
...            ...         ...            ...           ...        ...
13600         4907     หนองสูง             49      มุกดาหาร  16.494229
13607         4907     หนองสูง             49      มุกดาหาร  16.494229
13617         4907     หนองสูง             49      มุกดาหาร  16.494229
13625         4907     หนองสูง             49      มุกดาหาร  16.494229
13629         4907     หนองสูง             49      มุกดาหาร  16.494229

        longitude  ... time_weekofyear  time_quarter  time_is_weekend  \
4      104.350891  ...              18             2                0
18     104.350891  ...              18             2                0
26     104.350891  ...              18             2                0
30     104.350891  ...              18             2                0
35     104.350891  ...              18             2                0
...           ...  ...             ...           ...              ...
13600  104.350891  ...              30             3                1
13607  104.350891  ...              30             3                1
13617  104.350891  ...              30             3                1
13625  104.350891  ...              30             3                1
13629  104.350891  ...              30             3                1

       time_season  time_is_month_start  time_is_month_end  \
4                2                    0                  0
18               2                    0                  0
26               2                    0                  0
30               2                    0                  0
35               2                    0                  0
...            ...                  ...                ...
13600            3                    0                  1
13607            3                    0                  1
13617            3                    0                  1
13625            3                    0                  1
13629            3                    0                  1

       time_is_quarter_start  time_is_quarter_end  time_hour_sin  \
4                          0                    0       0.000000
18                         0                    0       0.707107
26                         0                    0       0.866025
30                         0                    0       0.965926
35                         0                    0       1.000000
...                      ...                  ...            ...
13600                      0                    0      -0.965926
13607                      0                    0      -1.000000
13617                      0                    0      -0.965926
13625                      0                    0      -0.866025
13629                      0                    0      -0.707107

       time_hour_cos
4       1.000000e+00
18      7.071068e-01
26      5.000000e-01
30      2.588190e-01
35      6.123234e-17
...              ...
13600  -2.588190e-01
13607  -1.836970e-16
13617   2.588190e-01
13625   5.000000e-01
13629   7.071068e-01

[1744 rows x 36 columns]

/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)

       index   station_name  tambon_code tambon_namt  amphur_code amphur_namt  \
5       3402  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
13      3007  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
17      2117  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
23      1729  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
33      1961  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
...      ...            ...          ...         ...          ...         ...
13603   2548  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
13610   3355  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
13613   2359  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
13621   3114  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล
13632   1806  บ้านนาสะแบง_2       380704     นาสะแบง         3807     ศรีวิไล

       province_code province_namt   latitude   longitude  ...  \
5                 38        บึงกาฬ  18.142499  103.806521  ...
13                38        บึงกาฬ  18.142499  103.806521  ...
17                38        บึงกาฬ  18.142499  103.806521  ...
23                38        บึงกาฬ  18.142499  103.806521  ...
33                38        บึงกาฬ  18.142499  103.806521  ...
...              ...           ...        ...         ...  ...
13603             38        บึงกาฬ  18.142499  103.806521  ...
13610             38        บึงกาฬ  18.142499  103.806521  ...
13613             38        บึงกาฬ  18.142499  103.806521  ...
13621             38        บึงกาฬ  18.142499  103.806521  ...
13632             38        บึงกาฬ  18.142499  103.806521  ...

      time_weekofyear  time_quarter  time_is_weekend  time_season  \
5                  18             2                0            2
13                 18             2                0            2
17                 18             2                0            2
23                 18             2                0            2
33                 18             2                0            2
...               ...           ...              ...          ...
13603              30             3                1            3
13610              30             3                1            3
13613              30             3                1            3
13621              30             3                1            3
13632              30             3                1            3

       time_is_month_start  time_is_month_end  time_is_quarter_start  \
5                        0                  0                      0
13                       0                  0                      0
17                       0                  0                      0
23                       0                  0                      0
33                       0                  0                      0
...                    ...                ...                    ...
13603                    0                  1                      0
13610                    0                  1                      0
13613                    0                  1                      0
13621                    0                  1                      0
13632                    0                  1                      0

       time_is_quarter_end  time_hour_sin  time_hour_cos
5                        0       0.000000   1.000000e+00
13                       0       0.500000   8.660254e-01
17                       0       0.707107   7.071068e-01
23                       0       0.866025   5.000000e-01
33                       0       0.965926   2.588190e-01
...                    ...            ...            ...
13603                    0      -0.965926  -2.588190e-01
13610                    0      -1.000000  -1.836970e-16
13613                    0      -0.965926   2.588190e-01
13621                    0      -0.866025   5.000000e-01
13632                    0      -0.707107   7.071068e-01

[1724 rows x 36 columns]
       index        station_name  tambon_code tambon_namt  amphur_code  \
6       5098  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
8       3522  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
11      4497  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
32      3441  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
39      3557  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
...      ...                 ...          ...         ...          ...
13596   4227  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
13606   5052  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
13615   4046  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
13623   4777  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308
13628   3475  บ้านสำโรงเกียรติ_2       330802      บักดอง         3308

      amphur_namt  province_code province_namt   latitude   longitude  ...  \
6          ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
8          ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
11         ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
32         ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
39         ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
...           ...            ...           ...        ...         ...  ...
13596      ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
13606      ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
13615      ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
13623      ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...
13628      ขุนหาญ             33      ศรีสะเกษ  14.533026  104.495172  ...

      time_weekofyear  time_quarter  time_is_weekend  time_season  \
6                  18             2                0            2
8                  18             2                0            2
11                 18             2                0            2
32                 18             2                0            2
39                 18             2                0            2
...               ...           ...              ...          ...
13596              30             3                1            3
13606              30             3                1            3
13615              30             3                1            3
13623              30             3                1            3
13628              30             3                1            3

       time_is_month_start  time_is_month_end  time_is_quarter_start  \
6                        0                  0                      0
8                        0                  0                      0
11                       0                  0                      0
32                       0                  0                      0
39                       0                  0                      0
...                    ...                ...                    ...
13596                    0                  1                      0
13606                    0                  1                      0
13615                    0                  1                      0
13623                    0                  1                      0
13628                    0                  1                      0

       time_is_quarter_end  time_hour_sin  time_hour_cos
6                        0       0.000000   1.000000e+00
8                        0       0.258819   9.659258e-01
11                       0       0.500000   8.660254e-01
32                       0       0.965926   2.588190e-01
39                       0       1.000000   6.123234e-17
...                    ...            ...            ...
13596                    0      -0.965926  -2.588190e-01
13606                    0      -1.000000  -1.836970e-16
13615                    0      -0.965926   2.588190e-01
13623                    0      -0.866025   5.000000e-01
13628                    0      -0.707107   7.071068e-01

[1696 rows x 36 columns]

/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)

       index         station_name  tambon_code tambon_namt  amphur_code  \
7      10145  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
15      9248  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
25      8484  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
38      8620  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
47     10002  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
...      ...                  ...          ...         ...          ...
13598   9283  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
13611  10099  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
13612   9100  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
13622   9845  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306
13633   8545  โรงเรียนสรรพวิทยาคม       630601      แม่สอด         6306

      amphur_namt  province_code province_namt  latitude  longitude  ...  \
7          แม่สอด             63           ตาก  16.71299  98.573417  ...
15         แม่สอด             63           ตาก  16.71299  98.573417  ...
25         แม่สอด             63           ตาก  16.71299  98.573417  ...
38         แม่สอด             63           ตาก  16.71299  98.573417  ...
47         แม่สอด             63           ตาก  16.71299  98.573417  ...
...           ...            ...           ...       ...        ...  ...
13598      แม่สอด             63           ตาก  16.71299  98.573417  ...
13611      แม่สอด             63           ตาก  16.71299  98.573417  ...
13612      แม่สอด             63           ตาก  16.71299  98.573417  ...
13622      แม่สอด             63           ตาก  16.71299  98.573417  ...
13633      แม่สอด             63           ตาก  16.71299  98.573417  ...

      time_weekofyear  time_quarter  time_is_weekend  time_season  \
7                  18             2                0            2
15                 18             2                0            2
25                 18             2                0            2
38                 18             2                0            2
47                 18             2                0            2
...               ...           ...              ...          ...
13598              30             3                1            3
13611              30             3                1            3
13612              30             3                1            3
13622              30             3                1            3
13633              30             3                1            3

       time_is_month_start  time_is_month_end  time_is_quarter_start  \
7                        0                  0                      0
15                       0                  0                      0
25                       0                  0                      0
38                       0                  0                      0
47                       0                  0                      0
...                    ...                ...                    ...
13598                    0                  1                      0
13611                    0                  1                      0
13612                    0                  1                      0
13622                    0                  1                      0
13633                    0                  1                      0

       time_is_quarter_end  time_hour_sin  time_hour_cos
7                        0       0.000000   1.000000e+00
15                       0       0.500000   8.660254e-01
25                       0       0.866025   5.000000e-01
38                       0       1.000000   6.123234e-17
47                       0       0.866025  -5.000000e-01
...                    ...            ...            ...
13598                    0      -0.965926  -2.588190e-01
13611                    0      -1.000000  -1.836970e-16
13612                    0      -0.965926   2.588190e-01
13622                    0      -0.866025   5.000000e-01
13633                    0      -0.707107   7.071068e-01

[1715 rows x 36 columns]

/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)
/tmp/ipython-input-134-1059688766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_copy[f'rolling_{feature_col}_{window}_{agg_function}'] = df_copy[feature_col].rolling(window=window).agg(agg_function)

### Visualize Dataset

In [ ]:
df_eda = df_train.copy()

In [ ]:
df_eda

In [ ]:
def plot_violin_box_distribution(df, columns):
    """
    Plots violin plots, box plots, and distribution plots for specified columns.

    Parameters:
        df (pd.DataFrame): The input DataFrame.
        columns (list): List of columns to plot.
    """
    # Filter columns that exist in the DataFrame
    valid_columns = [col for col in columns if col in df.columns]

    # Calculate the number of rows needed (3 plots per column)
    num_columns = len(valid_columns)
    num_rows = num_columns  # One row per column
    fig, axes = plt.subplots(num_rows, 3, figsize=(18, 5 * num_rows))

    # If only one column, axes will be 1D, so reshape it
    if num_columns == 1:
        axes = axes.reshape(1, -1)

    # Loop through the valid columns and plot
    for i, col in enumerate(valid_columns):
        # Violin Plot
        sns.violinplot(data=df, x=col, ax=axes[i, 0], palette='viridis')
        axes[i, 0].set_title(f'Violin Plot of {col}')
        axes[i, 0].set_xlabel(col)

        # Box Plot
        sns.boxplot(data=df, x=col, ax=axes[i, 1], palette='viridis')
        axes[i, 1].set_title(f'Box Plot of {col}')
        axes[i, 1].set_xlabel(col)

        # Distribution Plot (Histogram with KDE)
        sns.histplot(data=df, x=col, kde=True, ax=axes[i, 2], color='skyblue')
        axes[i, 2].set_title(f'Distribution of {col}')
        axes[i, 2].set_xlabel(col)
        axes[i, 2].set_ylabel('Density')

    # Adjust layout and display
    plt.tight_layout()
    plt.show()

In [ ]:
plot_violin_box_distribution(df_eda, columns=["temp", "pm2.5", "wind_speed"])

In [ ]:
plot_violin_box_distribution(df_eda, columns=["pm10", "rainfall", "wind_direct"])

In [ ]:
df_eda["pm2.5"].describe()

In [ ]:
df_eda["pm10"].describe()

In [ ]:
print(len(df_eda[df_eda['pm2.5'] >= 50]))
print(len(df_eda[df_eda['pm10'] >= 50]))

In [ ]:
df_eda['pm2.5'] = df_eda['pm2.5'].clip(6, 50)
df_eda['pm10'] = df_eda['pm10'].clip(6, 50)

In [ ]:
df_eda.info()

In [ ]:
df_eda = df_eda.drop(
    columns = [
        "tambon_code", "amphur_code", "province_code",
    ]
)

df_eda.describe()

### Check Duplicate Columns

In [ ]:
from collections import defaultdict

renamer = defaultdict()
renamer

In [ ]:
for column_name in df_eda.columns[df_eda.columns.duplicated(keep=False)].tolist():
    if column_name not in renamer:
      print(f"columns : {column_name}")
      #renamer[column_name] = [column_name+'_0']

    else:
      continue
      # renamer[column_name].append(column_name +'_'+str(len(renamer[column_name])))

In [ ]:
nan_rows = df_eda[df_eda.isnull().T.any()]
nan_rows

### Interpolation Fill Nan

In [ ]:
# Fill NaN values in 'PM2.5' column using interpolation in the new DataFrame
df_eda['pm2.5'] = df_eda['pm2.5'].interpolate(method='linear')
df_eda['pm10'] = df_eda['pm10'].interpolate(method='linear')
df_eda['temp'] = df_eda['temp'].interpolate(method='linear')

In [ ]:
nan_rows = df_eda[df_eda.isnull().T.any()]
nan_rows

In [ ]:
df_eda = df_eda.dropna()

nan_rows = df_eda[df_eda.isnull().T.any()]
nan_rows

## AutoGluon Tabular Predict

In [ ]:
!pip install autogluon

Requirement already satisfied: autogluon in /usr/local/lib/python3.11/dist-packages (1.3.1)
Requirement already satisfied: autogluon.core==1.3.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.core[all]==1.3.1->autogluon) (1.3.1)
Requirement already satisfied: autogluon.features==1.3.1 in /usr/local/lib/python3.11/dist-packages (from autogluon) (1.3.1)
Requirement already satisfied: autogluon.tabular==1.3.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (1.3.1)
Requirement already satisfied: autogluon.multimodal==1.3.1 in /usr/local/lib/python3.11/dist-packages (from autogluon) (1.3.1)
Requirement already satisfied: autogluon.timeseries==1.3.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries[all]==1.3.1->autogluon) (1.3.1)
Requirement already satisfied: numpy<2.3.0,>=1.25.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.16,>=1.5.4 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.15.3)
Requirement already satisfied: scikit-learn<1.7.0,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (3.5)
Requirement already satisfied: pandas<2.3.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2.2.2)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2.32.3)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (3.10.0)
Requirement already satisfied: boto3<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.39.3)
Requirement already satisfied: autogluon.common==1.3.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.3.1)
Requirement already satisfied: ray<2.45,>=2.10.0 in /usr/local/lib/python3.11/dist-packages (from ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (2.44.1)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.11/dist-packages (from autogluon.core[all]==1.3.1->autogluon) (0.2.7)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core[all]==1.3.1->autogluon) (18.1.0)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (11.2.1)
Requirement already satisfied: torch<2.7,>=2.2 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (2.6.0+cu124)
Requirement already satisfied: lightning<2.7,>=2.2 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (2.5.2)
Requirement already satisfied: transformers<4.50,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]<4.50,>=4.38.0->autogluon.multimodal==1.3.1->autogluon) (4.49.0)
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (1.8.1)
Requirement already satisfied: jsonschema<4.24,>=4.18 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (4.23.0)
Requirement already satisfied: seqeval<1.3.0,>=1.2.2 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (1.2.2)
Requirement already satisfied: evaluate<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (0.4.4)
Requirement already satisfied: timm<1.0.7,>=0.9.5 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (1.0.3)
Requirement already satisfied: torchvision<0.22.0,>=0.16.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (0.21.0+cu124)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (1.3)
Requirement already satisfied: torchmetrics<1.8,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (1.7.3)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (2.3.0)
Requirement already satisfied: pytorch-metric-learning<2.9,>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (2.8.1)
Requirement already satisfied: nlpaug<1.2.0,>=1.1.10 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (1.1.11)
Requirement already satisfied: nltk<3.9,>=3.4.5 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (3.8.1)
Requirement already satisfied: openmim<0.4.0,>=0.3.7 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (0.3.9)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (2.18.0)
Requirement already satisfied: pytesseract<0.4,>=0.3.9 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (0.3.13)
Requirement already satisfied: nvidia-ml-py3<8.0,>=7.352.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (7.352.0)
Requirement already satisfied: pdf2image<1.19,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.multimodal==1.3.1->autogluon) (1.17.0)
Requirement already satisfied: catboost<1.3,>=1.2 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (1.2.8)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (0.8.1)
Requirement already satisfied: xgboost<3.1,>=2.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (2.1.4)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (2.7.19)
Requirement already satisfied: huggingface-hub[torch] in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (0.33.1)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (4.5.0)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[all]==1.3.1->autogluon) (3.8.7)
Requirement already satisfied: joblib<2,>=1.1 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (1.5.1)
Requirement already satisfied: pytorch-lightning in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (2.5.2)
Requirement already satisfied: gluonts<0.17,>=0.15.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.16.2)
Requirement already satisfied: statsforecast<2.0.2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (2.0.1)
Requirement already satisfied: mlforecast<0.14,>0.13 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.13.6)
Requirement already satisfied: utilsforecast<0.2.11,>=0.2.3 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.2.10)
Requirement already satisfied: coreforecast<0.0.16,>=0.0.12 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.0.15)
Requirement already satisfied: fugue>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.9.1)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.11/dist-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (3.10.18)
Requirement already satisfied: psutil<7.1.0,>=5.7.3 in /usr/local/lib/python3.11/dist-packages (from autogluon.common==1.3.1->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (5.9.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.3.1->autogluon) (24.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.3.1->autogluon) (6.0.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.3.1->autogluon) (0.5.3)
Requirement already satisfied: botocore<1.40.0,>=1.39.3 in /usr/local/lib/python3.11/dist-packages (from boto3<2,>=1.10->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.39.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from boto3<2,>=1.10->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.0.1)
Requirement already satisfied: s3transfer<0.14.0,>=0.13.0 in /usr/local/lib/python3.11/dist-packages (from boto3<2,>=1.10->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (0.13.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.3.1->autogluon) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.3.1->autogluon) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.3.1->autogluon) (1.17.0)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (2.14.4)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (0.3.7)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (2025.3.2)
Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (24.1.2)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.11/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (0.0.7)
Requirement already satisfied: fastcore<1.8,>=1.5.29 in /usr/local/lib/python3.11/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (1.7.29)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.11/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (1.0.3)
Requirement already satisfied: triad>=0.9.7 in /usr/local/lib/python3.11/dist-packages (from fugue>=0.9.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.9.8)
Requirement already satisfied: adagio>=0.2.4 in /usr/local/lib/python3.11/dist-packages (from fugue>=0.9.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.2.6)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.11/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (2.11.7)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.11/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (4.14.0)
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.3.1->autogluon) (1.0.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.3.1->autogluon) (3.1.1)
Requirement already satisfied: py4j in /usr/local/lib/python3.11/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.3.1->autogluon) (0.10.9.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.3.1->autogluon) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (0.26.0)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from lightning<2.7,>=2.2->autogluon.multimodal==1.3.1->autogluon) (0.14.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2.9.0.post0)
Requirement already satisfied: numba in /usr/local/lib/python3.11/dist-packages (from mlforecast<0.14,>0.13->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.60.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.11/dist-packages (from mlforecast<0.14,>0.13->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (4.4.0)
Requirement already satisfied: window-ops in /usr/local/lib/python3.11/dist-packages (from mlforecast<0.14,>0.13->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.0.15)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.3.1->autogluon) (5.2.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk<3.9,>=3.4.5->autogluon.multimodal==1.3.1->autogluon) (8.2.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk<3.9,>=3.4.5->autogluon.multimodal==1.3.1->autogluon) (2024.11.6)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.11/dist-packages (from omegaconf<2.4.0,>=2.1.1->autogluon.multimodal==1.3.1->autogluon) (4.9.3)
Requirement already satisfied: colorama in /usr/local/lib/python3.11/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (0.4.6)
Requirement already satisfied: model-index in /usr/local/lib/python3.11/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (0.1.11)
Requirement already satisfied: opendatalab in /usr/local/lib/python3.11/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (0.0.10)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (13.9.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (0.9.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3.0,>=2.0.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3.0,>=2.0.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2025.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (3.18.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (1.1.1)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /usr/local/lib/python3.11/dist-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (5.29.5)
Requirement already satisfied: aiosignal in /usr/local/lib/python3.11/dist-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (1.3.2)
Requirement already satisfied: frozenlist in /usr/local/lib/python3.11/dist-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (1.7.0)
Requirement already satisfied: aiohttp>=3.7 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (3.11.15)

In [ ]:
from autogluon.tabular import TabularDataset, TabularPredictor
from autogluon.common import space

train_data = df_eda.copy()
label = 'temp'

# From hackathon
metric = 'mae'

In [ ]:
# nn_options = {  # specifies non-default hyperparameter values for neural network models
#     'num_epochs': 100,  # number of training epochs (controls training time of NN models)
#     'learning_rate': space.Real(1e-4, 1e-2, default=5e-4, log=True),  # learning rate used in training (real-valued hyperparameter searched on log-scale)
#     'activation': space.Categorical('relu', 'softrelu', 'tanh'),  # activation function used in NN (categorical hyperparameter, default = first entry)
#     'dropout_prob': space.Real(0.0, 0.5, default=0.1),  # dropout probability (real-valued hyperparameter)
# }

# gbm_options = {  # specifies non-default hyperparameter values for lightGBM gradient boosted trees
#     'num_boost_round': 100,  # number of boosting rounds (controls training time of GBM models)
#     'num_leaves': space.Int(lower=26, upper=66, default=36),  # number of leaves in trees (integer hyperparameter)
# }

#  # NOTE: comment this line out if you get errors on Mac OSX
# hyperparameters = { # hyperparameters of each model type
#                    'GBM': gbm_options,
#                     # NOTE: comment this line out if you get errors on Mac OSX
#                    'NN_TORCH': nn_options,
#                   }

# time_limit = 10*60  # train various models for ~2 min
# num_trials = 5  # try at most 5 different hyperparameter configurations for each type of model
# search_strategy = 'auto'  # to tune hyperparameters using random search routine with a local scheduler

# hyperparameter_tune_kwargs = {  # HPO is not performed unless hyperparameter_tune_kwargs is specified
#     'num_trials': num_trials,
#     'scheduler' : 'local',
#     'searcher': search_strategy,
# }

predictor = TabularPredictor(label=label, eval_metric=metric).fit(
    train_data,
    # time_limit=time_limit,
    # hyperparameters=hyperparameters,
    # hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
    presets='best_quality',
)

No path specified. Models will be saved in: "AutogluonModels/ag-20250705_092231"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Sun Mar 30 16:01:29 UTC 2025
CPU Count:          12
Memory Avail:       50.77 GB / 52.96 GB (95.9%)
Disk Space Avail:   192.89 GB / 235.68 GB (81.8%)
===================================================
Presets specified: ['best_quality']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 150s of the 600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2025-07-05 09:22:33,577	INFO worker.py:1843 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
		Context path: "/content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho"
(_dystack pid=9043) Running DyStack sub-fit ...
(_dystack pid=9043) Beginning AutoGluon training ... Time limit = 147s
(_dystack pid=9043) AutoGluon will save models to "/content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho"
(_dystack pid=9043) Train Data Rows:    12119
(_dystack pid=9043) Train Data Columns: 30
(_dystack pid=9043) Label Column:       temp
(_dystack pid=9043) Problem Type:       regression
(_dystack pid=9043) Preprocessing data ...
(_dystack pid=9043) Using Feature Generators to preprocess the data ...
(_dystack pid=9043) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=9043) 	Available Memory:                    51228.78 MB
(_dystack pid=9043) 	Train Data (Original)  Memory Usage: 6.70 MB (0.0% of available memory)
(_dystack pid=9043) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=9043) 	Stage 1 Generators:
(_dystack pid=9043) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=9043) 			Note: Converting 7 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=9043) 	Stage 2 Generators:
(_dystack pid=9043) 		Fitting FillNaFeatureGenerator...
(_dystack pid=9043) 	Stage 3 Generators:
(_dystack pid=9043) 		Fitting IdentityFeatureGenerator...
(_dystack pid=9043) 		Fitting CategoryFeatureGenerator...
(_dystack pid=9043) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=9043) 	Stage 4 Generators:
(_dystack pid=9043) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=9043) 	Stage 5 Generators:
(_dystack pid=9043) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=9043) 	Useless Original Features (Count: 2): ['time_minute', 'time_second']
(_dystack pid=9043) 		These features carry no predictive signal and should be manually investigated.
(_dystack pid=9043) 		This is typically a feature which has the same value for all rows.
(_dystack pid=9043) 		These features do not need to be present at inference time.
(_dystack pid=9043) 	Unused Original Features (Count: 3): ['tambon_namt', 'amphur_namt', 'province_namt']
(_dystack pid=9043) 		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
(_dystack pid=9043) 		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
(_dystack pid=9043) 		These features do not need to be present at inference time.
(_dystack pid=9043) 		('object', []) : 3 | ['tambon_namt', 'amphur_namt', 'province_namt']
(_dystack pid=9043) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=9043) 		('float', [])  : 11 | ['latitude', 'longitude', 'humid', 'light', 'pm10', ...]
(_dystack pid=9043) 		('int', [])    : 13 | ['time_month', 'time_day', 'time_hour', 'time_dayofweek', 'time_dayofyear', ...]
(_dystack pid=9043) 		('object', []) :  1 | ['station_name']
(_dystack pid=9043) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=9043) 		('category', [])  :  1 | ['station_name']
(_dystack pid=9043) 		('float', [])     : 11 | ['latitude', 'longitude', 'humid', 'light', 'pm10', ...]
(_dystack pid=9043) 		('int', [])       :  6 | ['time_month', 'time_day', 'time_hour', 'time_dayofweek', 'time_dayofyear', ...]
(_dystack pid=9043) 		('int', ['bool']) :  7 | ['time_quarter', 'time_is_weekend', 'time_season', 'time_is_month_start', 'time_is_month_end', ...]
(_dystack pid=9043) 	0.4s = Fit runtime
(_dystack pid=9043) 	25 features in original data used to generate 25 features in processed data.
(_dystack pid=9043) 	Train Data (Processed) Memory Usage: 1.43 MB (0.0% of available memory)
(_dystack pid=9043) Data preprocessing and feature engineering runtime = 0.39s ...
(_dystack pid=9043) AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
(_dystack pid=9043) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=9043) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=9043) User-specified model hyperparameters to be fit:
(_dystack pid=9043) {
(_dystack pid=9043) 	'GBM': [{'num_boost_round': 100, 'num_leaves': Int: lower=26, upper=66}],
(_dystack pid=9043) 	'NN_TORCH': [{'num_epochs': 100, 'learning_rate': Real: lower=0.0001, upper=0.01, 'activation': Categorical['relu', 'softrelu', 'tanh'], 'dropout_prob': Real: lower=0.0, upper=0.5}],
(_dystack pid=9043) }
(_dystack pid=9043) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=9043) Fitting 2 L1 models, fit_strategy="sequential" ...
(_dystack pid=9043) Hyperparameter tuning model: LightGBM_BAG_L1 ... Tuning model for up to 44.07s of the 146.95s of remaining time.
  0%|          | 0/5 [00:00<?, ?it/s]	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
 20%|██        | 1/5 [00:05<00:21,  5.41s/it]
(_dystack pid=9043) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
 40%|████      | 2/5 [00:10<00:15,  5.23s/it]	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
 60%|██████    | 3/5 [00:15<00:10,  5.22s/it]
(_dystack pid=9043) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
 80%|████████  | 4/5 [00:21<00:05,  5.28s/it]
(_dystack pid=9043) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
100%|██████████| 5/5 [00:26<00:00,  5.26s/it]
(_dystack pid=9043) Fitted model: LightGBM_BAG_L1/T1 ...
(_dystack pid=9043) 	-0.6159	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.4s	 = Training   runtime
(_dystack pid=9043) 	0.13s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L1/T2 ...
(_dystack pid=9043) 	-0.577	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.09s	 = Training   runtime
(_dystack pid=9043) 	0.13s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L1/T3 ...
(_dystack pid=9043) 	-0.6028	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.2s	 = Training   runtime
(_dystack pid=9043) 	0.16s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L1/T4 ...
(_dystack pid=9043) 	-2.0581	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.35s	 = Training   runtime
(_dystack pid=9043) 	0.1s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L1/T5 ...
(_dystack pid=9043) 	-0.6681	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.21s	 = Training   runtime
(_dystack pid=9043) 	0.13s	 = Validation runtime
(_dystack pid=9043) Hyperparameter tuning model: NeuralNetTorch_BAG_L1 ... Tuning model for up to 44.07s of the 120.6s of remaining time.

(_dystack pid=9043) ╭──────────────────────────────────────────────────────────╮
(_dystack pid=9043) │ Configuration for experiment     NeuralNetTorch_BAG_L1   │
(_dystack pid=9043) ├──────────────────────────────────────────────────────────┤
(_dystack pid=9043) │ Search algorithm                 SearchGenerator         │
(_dystack pid=9043) │ Scheduler                        FIFOScheduler           │
(_dystack pid=9043) │ Number of trials                 5                       │
(_dystack pid=9043) ╰──────────────────────────────────────────────────────────╯
(_dystack pid=9043)
(_dystack pid=9043) View detailed results here: /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L1

(_ray_fit pid=11890) 	Ran out of time, stopping training early. (Stopping on epoch 96)
(_dystack pid=9043) Reached timeout of 44.07339190067053 seconds. Stopping all trials.
(_dystack pid=9043) Wrote the latest version of all result files and experiment state to '/content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L1' in 0.0069s.
(_ray_fit pid=11888) 	Ran out of time, stopping training early. (Stopping on epoch 99) [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_dystack pid=9043) Failed to fetch metrics for 3 trial(s):
(_dystack pid=9043) - 1e89b1cf: FileNotFoundError('Could not fetch metrics for 1e89b1cf: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L1/1e89b1cf')
(_dystack pid=9043) - 78abd6fb: FileNotFoundError('Could not fetch metrics for 78abd6fb: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L1/78abd6fb')
(_dystack pid=9043) - 89bd3e8f: FileNotFoundError('Could not fetch metrics for 89bd3e8f: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L1/89bd3e8f')
(_dystack pid=9043) Fitted model: NeuralNetTorch_BAG_L1/1e89b1cf ...
(_dystack pid=9043) 	-0.6111	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	34.34s	 = Training   runtime
(_dystack pid=9043) 	0.13s	 = Validation runtime
(_dystack pid=9043) Fitting model: WeightedEnsemble_L2 ... Training model for up to 146.95s of the 74.56s of remaining time.
(_dystack pid=9043) 	Ensemble Weights: {'LightGBM_BAG_L1/T2': 0.542, 'NeuralNetTorch_BAG_L1/1e89b1cf': 0.375, 'LightGBM_BAG_L1/T3': 0.083}
(_dystack pid=9043) 	-0.5546	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	0.07s	 = Training   runtime
(_dystack pid=9043) 	0.0s	 = Validation runtime
(_dystack pid=9043) Fitting 2 L2 models, fit_strategy="sequential" ...
(_dystack pid=9043) Hyperparameter tuning model: LightGBM_BAG_L2 ... Tuning model for up to 33.51s of the 74.47s of remaining time.

(_dystack pid=9043)

  0%|          | 0/5 [00:00<?, ?it/s]	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
 20%|██        | 1/5 [00:05<00:20,  5.15s/it]
(_dystack pid=9043) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
 40%|████      | 2/5 [00:10<00:15,  5.13s/it]
(_dystack pid=9043) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.05%)
 60%|██████    | 3/5 [00:15<00:10,  5.31s/it]	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
 80%|████████  | 4/5 [00:21<00:05,  5.28s/it]	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
100%|██████████| 5/5 [00:26<00:00,  5.24s/it]
(_dystack pid=9043) Fitted model: LightGBM_BAG_L2/T1 ...
(_dystack pid=9043) 	-0.5392	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.15s	 = Training   runtime
(_dystack pid=9043) 	0.12s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L2/T2 ...
(_dystack pid=9043) 	-0.5306	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.1s	 = Training   runtime
(_dystack pid=9043) 	0.1s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L2/T3 ...
(_dystack pid=9043) 	-0.538	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.52s	 = Training   runtime
(_dystack pid=9043) 	0.16s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L2/T4 ...
(_dystack pid=9043) 	-1.9329	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.22s	 = Training   runtime
(_dystack pid=9043) 	0.08s	 = Validation runtime
(_dystack pid=9043) Fitted model: LightGBM_BAG_L2/T5 ...
(_dystack pid=9043) 	-0.5511	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	5.17s	 = Training   runtime
(_dystack pid=9043) 	0.12s	 = Validation runtime
(_dystack pid=9043) Hyperparameter tuning model: NeuralNetTorch_BAG_L2 ... Tuning model for up to 33.51s of the 48.24s of remaining time.

(_dystack pid=9043) ╭──────────────────────────────────────────────────────────╮
(_dystack pid=9043) │ Configuration for experiment     NeuralNetTorch_BAG_L2   │
(_dystack pid=9043) ├──────────────────────────────────────────────────────────┤
(_dystack pid=9043) │ Search algorithm                 SearchGenerator         │
(_dystack pid=9043) │ Scheduler                        FIFOScheduler           │
(_dystack pid=9043) │ Number of trials                 5                       │
(_dystack pid=9043) ╰──────────────────────────────────────────────────────────╯
(_dystack pid=9043)
(_dystack pid=9043) View detailed results here: /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L2

(_dystack pid=9043) Reached timeout of 33.51452511548996 seconds. Stopping all trials.
(_dystack pid=9043) Wrote the latest version of all result files and experiment state to '/content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L2' in 0.0067s.
(_dystack pid=9043) Failed to fetch metrics for 3 trial(s):
(_dystack pid=9043) - 42a36f66: FileNotFoundError('Could not fetch metrics for 42a36f66: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L2/42a36f66')
(_dystack pid=9043) - 30bef575: FileNotFoundError('Could not fetch metrics for 30bef575: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L2/30bef575')
(_dystack pid=9043) - ef588f60: FileNotFoundError('Could not fetch metrics for ef588f60: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho/models/NeuralNetTorch_BAG_L2/ef588f60')
(_dystack pid=9043) Fitted model: NeuralNetTorch_BAG_L2/42a36f66 ...
(_dystack pid=9043) 	-0.5727	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	24.57s	 = Training   runtime
(_dystack pid=9043) 	0.14s	 = Validation runtime
(_dystack pid=9043) Fitting model: WeightedEnsemble_L3 ... Training model for up to 146.95s of the 12.55s of remaining time.
(_dystack pid=9043) 	Ensemble Weights: {'LightGBM_BAG_L2/T2': 0.76, 'LightGBM_BAG_L2/T3': 0.16, 'NeuralNetTorch_BAG_L1/1e89b1cf': 0.04, 'NeuralNetTorch_BAG_L2/42a36f66': 0.04}
(_dystack pid=9043) 	-0.5299	 = Validation score   (-mean_absolute_error)
(_dystack pid=9043) 	0.08s	 = Training   runtime
(_dystack pid=9043) 	0.0s	 = Validation runtime
(_dystack pid=9043) AutoGluon training complete, total runtime = 134.89s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 1404.7 rows/s (1515 batch size)
(_dystack pid=9043) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20250705_092231/ds_sub_fit/sub_fit_ho")

(_dystack pid=9043)

(_dystack pid=9043) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                             model  score_holdout  score_val          eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0              WeightedEnsemble_L3      -0.528133  -0.529852  mean_absolute_error        5.182396       1.079267  90.524759                 0.002388                0.000815           0.079984            3       True         14
1               LightGBM_BAG_L2/T2      -0.528679  -0.530592  mean_absolute_error        4.949934       0.776390  60.351603                 0.054708                0.101423           5.102272            2       True          9
2               LightGBM_BAG_L2/T3      -0.531610  -0.538042  mean_absolute_error        5.009661       0.833934  60.768011                 0.114435                0.158967           5.518680            2       True         10
3               LightGBM_BAG_L2/T1      -0.536450  -0.539173  mean_absolute_error        4.987852       0.792030  60.397586                 0.092625                0.117063           5.148255            2       True          8
4               LightGBM_BAG_L2/T5      -0.551064  -0.551122  mean_absolute_error        5.003362       0.794578  60.414956                 0.108135                0.119611           5.165625            2       True         12
5              WeightedEnsemble_L2      -0.560464  -0.554583  mean_absolute_error        2.052316       0.412689  44.703688                 0.002233                0.000849           0.068050            2       True          7
6   NeuralNetTorch_BAG_L2/42a36f66      -0.563383  -0.572679  mean_absolute_error        5.010866       0.818063  79.823823                 0.115639                0.143095          24.574492            2       True         13
7               LightGBM_BAG_L1/T2      -0.583419  -0.576988  mean_absolute_error        0.036381       0.126391   5.092429                 0.036381                0.126391           5.092429            1       True          2
8   NeuralNetTorch_BAG_L1/1e89b1cf      -0.588738  -0.611130  mean_absolute_error        1.968776       0.125542  34.341154                 1.968776                0.125542          34.341154            1       True          6
9               LightGBM_BAG_L1/T3      -0.616835  -0.602774  mean_absolute_error        0.044926       0.159906   5.202055                 0.044926                0.159906           5.202055            1       True          3
10              LightGBM_BAG_L1/T1      -0.626703  -0.615857  mean_absolute_error        2.806190       0.131469   5.403028                 2.806190                0.131469           5.403028            1       True          1
11              LightGBM_BAG_L1/T5      -0.680433  -0.668064  mean_absolute_error        0.038954       0.131659   5.210664                 0.038954                0.131659           5.210664            1       True          5
12              LightGBM_BAG_L2/T4      -1.964928  -1.932915  mean_absolute_error        5.021508       0.753332  60.469045                 0.126282                0.078364           5.219714            2       True         11
13              LightGBM_BAG_L1/T4      -2.100149  -2.058058  mean_absolute_error        0.033336       0.100068   5.352726                 0.033336                0.100068           5.352726            1       True          4
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	145s	 = DyStack   runtime |	455s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 455s
AutoGluon will save models to "/content/AutogluonModels/ag-20250705_092231"
Train Data Rows:    13634
Train Data Columns: 30
Label Column:       temp
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    50649.70 MB
	Train Data (Original)  Memory Usage: 9.11 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 7 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 2): ['time_minute', 'time_second']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 3): ['tambon_namt', 'amphur_namt', 'province_namt']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 3 | ['tambon_namt', 'amphur_namt', 'province_namt']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 11 | ['latitude', 'longitude', 'humid', 'light', 'pm10', ...]
		('int', [])    : 13 | ['time_month', 'time_day', 'time_hour', 'time_dayofweek', 'time_dayofyear', ...]
		('object', []) :  1 | ['station_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  1 | ['station_name']
		('float', [])     : 11 | ['latitude', 'longitude', 'humid', 'light', 'pm10', ...]
		('int', [])       :  6 | ['time_month', 'time_day', 'time_hour', 'time_dayofweek', 'time_dayofyear', ...]
		('int', ['bool']) :  7 | ['time_quarter', 'time_is_weekend', 'time_season', 'time_is_month_start', 'time_is_month_end', ...]
	0.4s = Fit runtime
	25 features in original data used to generate 25 features in processed data.
	Train Data (Processed) Memory Usage: 1.61 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.42s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_boost_round': 100, 'num_leaves': Int: lower=26, upper=66}],
	'NN_TORCH': [{'num_epochs': 100, 'learning_rate': Real: lower=0.0001, upper=0.01, 'activation': Categorical['relu', 'softrelu', 'tanh'], 'dropout_prob': Real: lower=0.0, upper=0.5}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM_BAG_L1 ... Tuning model for up to 136.35s of the 454.61s of remaining time.

  0%|          | 0/5 [00:00<?, ?it/s]

	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.03%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
Fitted model: LightGBM_BAG_L1/T1 ...
	-0.609	 = Validation score   (-mean_absolute_error)
	5.25s	 = Training   runtime
	0.14s	 = Validation runtime
Fitted model: LightGBM_BAG_L1/T2 ...
	-0.5742	 = Validation score   (-mean_absolute_error)
	5.15s	 = Training   runtime
	0.13s	 = Validation runtime
Fitted model: LightGBM_BAG_L1/T3 ...
	-0.5932	 = Validation score   (-mean_absolute_error)
	5.5s	 = Training   runtime
	0.18s	 = Validation runtime
Fitted model: LightGBM_BAG_L1/T4 ...
	-2.063	 = Validation score   (-mean_absolute_error)
	5.09s	 = Training   runtime
	0.1s	 = Validation runtime
Fitted model: LightGBM_BAG_L1/T5 ...
	-0.6657	 = Validation score   (-mean_absolute_error)
	5.26s	 = Training   runtime
	0.14s	 = Validation runtime
Hyperparameter tuning model: NeuralNetTorch_BAG_L1 ... Tuning model for up to 136.35s of the 428.24s of remaining time.

+----------------------------------------------------------+
| Configuration for experiment     NeuralNetTorch_BAG_L1   |
+----------------------------------------------------------+
| Search algorithm                 SearchGenerator         |
| Scheduler                        FIFOScheduler           |
| Number of trials                 5                       |
+----------------------------------------------------------+

View detailed results here: /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L1

2025-07-05 09:27:40,668	INFO timeout.py:54 -- Reached timeout of 136.35051085336804 seconds. Stopping all trials.
2025-07-05 09:27:40,677	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L1' in 0.0072s.
2025-07-05 09:27:42,093	WARNING experiment_analysis.py:180 -- Failed to fetch metrics for 4 trial(s):
- 305d92ce: FileNotFoundError('Could not fetch metrics for 305d92ce: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L1/305d92ce')
- 0aca1bca: FileNotFoundError('Could not fetch metrics for 0aca1bca: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L1/0aca1bca')
- 97215195: FileNotFoundError('Could not fetch metrics for 97215195: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L1/97215195')
- 431765e5: FileNotFoundError('Could not fetch metrics for 431765e5: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L1/431765e5')
Fitted model: NeuralNetTorch_BAG_L1/305d92ce ...
	-0.5948	 = Validation score   (-mean_absolute_error)
	37.93s	 = Training   runtime
	0.13s	 = Validation runtime
Fitted model: NeuralNetTorch_BAG_L1/0aca1bca ...
	-0.5419	 = Validation score   (-mean_absolute_error)
	75.07s	 = Training   runtime
	0.98s	 = Validation runtime
Fitted model: NeuralNetTorch_BAG_L1/97215195 ...
	-7.8014	 = Validation score   (-mean_absolute_error)
	11.62s	 = Training   runtime
	0.2s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 289.84s of remaining time.
	Ensemble Weights: {'NeuralNetTorch_BAG_L1/0aca1bca': 0.522, 'LightGBM_BAG_L1/T2': 0.261, 'NeuralNetTorch_BAG_L1/305d92ce': 0.217}
	-0.5066	 = Validation score   (-mean_absolute_error)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 2 L2 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM_BAG_L2 ... Tuning model for up to 130.38s of the 289.72s of remaining time.

  0%|          | 0/5 [00:00<?, ?it/s]

	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.05%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
Fitted model: LightGBM_BAG_L2/T1 ...
	-0.4994	 = Validation score   (-mean_absolute_error)
	5.36s	 = Training   runtime
	0.13s	 = Validation runtime
Fitted model: LightGBM_BAG_L2/T2 ...
	-0.4943	 = Validation score   (-mean_absolute_error)
	5.15s	 = Training   runtime
	0.1s	 = Validation runtime
Fitted model: LightGBM_BAG_L2/T3 ...
	-0.4996	 = Validation score   (-mean_absolute_error)
	5.53s	 = Training   runtime
	0.16s	 = Validation runtime
Fitted model: LightGBM_BAG_L2/T4 ...
	-1.9303	 = Validation score   (-mean_absolute_error)
	5.28s	 = Training   runtime
	0.09s	 = Validation runtime
Fitted model: LightGBM_BAG_L2/T5 ...
	-0.5097	 = Validation score   (-mean_absolute_error)
	5.27s	 = Training   runtime
	0.13s	 = Validation runtime
Hyperparameter tuning model: NeuralNetTorch_BAG_L2 ... Tuning model for up to 130.38s of the 263.02s of remaining time.

+----------------------------------------------------------+
| Configuration for experiment     NeuralNetTorch_BAG_L2   |
+----------------------------------------------------------+
| Search algorithm                 SearchGenerator         |
| Scheduler                        FIFOScheduler           |
| Number of trials                 5                       |
+----------------------------------------------------------+

View detailed results here: /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L2

2025-07-05 09:30:19,547	INFO timeout.py:54 -- Reached timeout of 130.37792751789092 seconds. Stopping all trials.
2025-07-05 09:30:19,556	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L2' in 0.0081s.
2025-07-05 09:30:20,128	WARNING experiment_analysis.py:180 -- Failed to fetch metrics for 5 trial(s):
- 159261aa: FileNotFoundError('Could not fetch metrics for 159261aa: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L2/159261aa')
- 07553bf1: FileNotFoundError('Could not fetch metrics for 07553bf1: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L2/07553bf1')
- a9e97997: FileNotFoundError('Could not fetch metrics for a9e97997: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L2/a9e97997')
- c222f18b: FileNotFoundError('Could not fetch metrics for c222f18b: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L2/c222f18b')
- 9b9d1c24: FileNotFoundError('Could not fetch metrics for 9b9d1c24: both result.json and progress.csv were not found at /content/AutogluonModels/ag-20250705_092231/models/NeuralNetTorch_BAG_L2/9b9d1c24')
Fitted model: NeuralNetTorch_BAG_L2/159261aa ...
	-0.5317	 = Validation score   (-mean_absolute_error)
	26.68s	 = Training   runtime
	0.14s	 = Validation runtime
Fitted model: NeuralNetTorch_BAG_L2/07553bf1 ...
	-0.5817	 = Validation score   (-mean_absolute_error)
	53.22s	 = Training   runtime
	0.26s	 = Validation runtime
Fitted model: NeuralNetTorch_BAG_L2/a9e97997 ...
	-0.6775	 = Validation score   (-mean_absolute_error)
	33.39s	 = Training   runtime
	0.32s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 131.80s of remaining time.
	Ensemble Weights: {'LightGBM_BAG_L2/T2': 0.64, 'LightGBM_BAG_L2/T3': 0.12, 'NeuralNetTorch_BAG_L1/0aca1bca': 0.08, 'NeuralNetTorch_BAG_L2/159261aa': 0.08, 'NeuralNetTorch_BAG_L1/305d92ce': 0.04, 'NeuralNetTorch_BAG_L2/07553bf1': 0.04}
	-0.4926	 = Validation score   (-mean_absolute_error)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 323.36s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 663.7 rows/s (1705 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20250705_092231")

## Transform Data Test

In [ ]:
df_test = pd.read_csv("/content/IOT_Test.csv")
df_submission = pd.read_csv("/content/IOT_Submit.csv")
df_test

,id,mac,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,time,humid,light,pm10,pm2.5,rainfall,wind_direct,wind_speed
0,1,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-23 04:00:00+07:00,88.9,1.0,NaN,NaN,0.0,180.0,2.3
1,2,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-12 16:00:00+07:00,85.0,40.0,NaN,NaN,0.3,135.0,1.5
2,3,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-06-20 03:00:00+07:00,88.9,7.0,NaN,NaN,0.0,157.5,0.0
3,4,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-13 13:00:00+07:00,81.9,66.0,NaN,NaN,0.0,135.0,0.2
4,5,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-05 09:00:00+07:00,64.9,71.0,NaN,NaN,0.0,225.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3408,3409,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-06-05 03:00:00+07:00,87.0,0.0,NaN,NaN,0.0,315.0,0.0
3409,3410,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-26 09:00:00+07:00,71.7,81.0,NaN,NaN,0.0,180.0,3.1
3410,3411,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-21 22:00:00+07:00,86.5,2.0,NaN,NaN,0.0,0.0,0.6
3411,3412,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-07-21 01:00:00+07:00,96.5,0.0,NaN,NaN,0.0,0.0,0.0
3412,3413,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-06-20 11:00:00+07:00,63.8,87.0,1.0,0.0,0.0,0.0,0.4

In [ ]:
df_test["temp"] = np.nan

In [ ]:
# Format Time
df_test["time"] = pd.to_datetime(df_test["time"])
df_test = df_test.sort_values(by="id")
df_test = extract_time_features(df=df_test, time_columns=["time"])
df_test = df_test.drop(columns=["time", "time_dt", "mac", "time_year", "time_is_year_start", "time_is_year_end"])
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3413 entries, 0 to 3412
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3413 non-null   int64
 1   station_name           3413 non-null   object
 2   tambon_code            3413 non-null   int64
 3   tambon_namt            3413 non-null   object
 4   amphur_code            3413 non-null   int64
 5   amphur_namt            3413 non-null   object
 6   province_code          3413 non-null   int64
 7   province_namt          3413 non-null   object
 8   latitude               3413 non-null   float64
 9   longitude              3413 non-null   float64
 10  humid                  3413 non-null   float64
 11  light                  3413 non-null   float64
 12  pm10                   1687 non-null   float64
 13  pm2.5                  1687 non-null   float64
 14  rainfall               3413 non-null   float64
 15  wind_direct            3413 non-null   float64
 16  wind_speed             3413 non-null   float64
 17  temp                   0 non-null      float64
 18  time_month             3413 non-null   int32
 19  time_day               3413 non-null   int32
 20  time_hour              3413 non-null   int32
 21  time_minute            3413 non-null   int32
 22  time_second            3413 non-null   int32
 23  time_dayofweek         3413 non-null   int32
 24  time_dayofyear         3413 non-null   int32
 25  time_weekofyear        3413 non-null   int64
 26  time_quarter           3413 non-null   int32
 27  time_is_weekend        3413 non-null   int64
 28  time_season            3413 non-null   int32
 29  time_is_month_start    3413 non-null   int64
 30  time_is_month_end      3413 non-null   int64
 31  time_is_quarter_start  3413 non-null   int64
 32  time_is_quarter_end    3413 non-null   int64
 33  time_hour_sin          3413 non-null   float64
 34  time_hour_cos          3413 non-null   float64
dtypes: float64(12), int32(9), int64(10), object(4)
memory usage: 813.4+ KB

/tmp/ipython-input-9-1301132536.py:61: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df_copy[f'{col}_dt'] = pd.to_datetime(df_copy[col], errors='coerce', infer_datetime_format=True)

In [ ]:
# Clip
df_test['pm2.5'] = df_test['pm2.5'].clip(6, 50)
df_test['pm10'] = df_test['pm10'].clip(6, 50)

# Interpolation
df_test['pm2.5'] = df_test['pm2.5'].interpolate(method='linear')
df_test['pm10'] = df_test['pm10'].interpolate(method='linear')

In [ ]:
df_test

,id,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,...,time_weekofyear,time_quarter,time_is_weekend,time_season,time_is_month_start,time_is_month_end,time_is_quarter_start,time_is_quarter_end,time_hour_sin,time_hour_cos
0,1,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,...,21,2,0,2,0,0,0,0,0.866025,0.500000
1,2,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,...,19,2,0,2,0,0,0,0,-0.866025,-0.500000
2,3,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,...,25,2,0,3,0,0,0,0,0.707107,0.707107
3,4,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,...,28,3,0,3,0,0,0,0,-0.258819,-0.965926
4,5,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,...,27,3,0,3,0,0,0,0,0.707107,-0.707107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3408,3409,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,...,22,2,1,3,0,0,0,0,0.707107,0.707107
3409,3410,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,...,21,2,0,2,0,0,0,0,0.707107,-0.707107
3410,3411,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,...,20,2,1,2,0,0,0,0,-0.500000,0.866025
3411,3412,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,...,29,3,0,3,0,0,0,0,0.258819,0.965926
3412,3413,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,...,25,2,0,3,0,0,0,0,0.258819,-0.965926

## Prediction

In [ ]:
y_pred = predictor.predict(df_test.drop(columns=[label]))
y_pred.head()

0    25.475311
1    28.583195
2    25.046091
3    29.336971
4    34.380157
Name: temp, dtype: float32

In [ ]:
y_pred = y_pred.reset_index()
y_pred = y_pred.rename(columns={"index":"id"})
y_pred["id"] = y_pred["id"] + 1

In [ ]:
y_pred

        id       temp
0        1  25.475311
1        2  28.583195
2        3  25.046091
3        4  29.336971
4        5  34.380157
...    ...        ...
3408  3409  25.764868
3409  3410  32.715298
3410  3411  26.925190
3411  3412  24.783997
3412  3413  36.143593

[3413 rows x 2 columns]

In [ ]:
df_submission

        id  temp
0        1  25.6
1        2  30.1
2        3  24.7
3        4   NaN
4        5   NaN
...    ...   ...
3408  3409   NaN
3409  3410   NaN
3410  3411   NaN
3411  3412   NaN
3412  3413   NaN

[3413 rows x 2 columns]

In [ ]:
y_pred.to_csv("Tabular_Gluon_TimeExtractorOnly.csv")